import io,json,tempfile,unittest,wave
import contextlib
from pathlib import Path
from qingshan_review.core import Reviewer,stable_issue,repair_task,timeout_decision,score_issues,deduplicate_issues,adjudicate_audio_cut,audio_pcm,sanitize_issue_time_ranges,probe_image
from qingshan_review.agent import Agent
from qingshan_review.cli import main as cli_main
from qingshan_review.shot_recipe import audit_shot_recipe

class Tests(unittest.TestCase):
 def wav(self,zero=True):
  d=tempfile.TemporaryDirectory();p=Path(d.name)/"x.wav"
  with wave.open(str(p),"wb") as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes((b"\0\0" if zero else b"\xe8\x03")*8000)
  return d,p
 def test_stable_id(self):
  p=Path("/tmp/a.mp4");a=stable_issue("x",p,{"start_seconds":1});b=stable_issue("x",p,{"start_seconds":1});self.assertEqual(a["issue_id"],b["issue_id"])
 def test_zero_audio_blocks(self):
  d,p=self.wav();r=Reviewer().review({"path":str(p),"kind":"audio"});self.assertEqual(r["status"],"FAIL");self.assertTrue(any(x["rule_id"]=="audio.digital_zero" for x in r["issues"]));d.cleanup()
 def test_ndjson_health(self):
  inp=io.StringIO('{"id":"1","method":"health"}\n');out=io.StringIO();Agent(Reviewer()).serve(inp,out);z=json.loads(out.getvalue());self.assertTrue(z["ok"]);self.assertEqual(z["result"]["workers"],4)
 def test_repair_no_publish(self):
  d,p=self.wav();r=Reviewer().review({"path":str(p),"kind":"audio","clip_id":"c1"});t=repair_task(r);self.assertFalse(t["publish_allowed"]);self.assertEqual(t["clip_id"],"c1");d.cleanup()
 def test_append_only_registry(self):
  d,p=self.wav(); reg=Path(d.name)/"rules.ndjson";rev=Reviewer(registry=reg);report=rev.review({"path":str(p),"kind":"audio"});rev.promote(report["issues"][0],"NO_ZERO");rev.promote(report["issues"][0],"NO_ZERO_2");self.assertEqual(len(reg.read_text().splitlines()),2);d.cleanup()
 def test_timeout_and_protected_actions(self):
  original={"status":"PASS","issues":[]};self.assertEqual(timeout_decision(original,901)["machine_decision"],"ACCEPT");self.assertEqual(timeout_decision(original,901,protected_reason="copyright")["state"],"HUMAN_REQUIRED_PROTECTED")
 def test_importance_changes_threshold(self):
  issue=stable_issue("soft",Path("/tmp/a.mp4"),{},"error",1,blocking=False)
  self.assertTrue(score_issues([issue],"utility")["passed"])
  self.assertFalse(score_issues([issue],"critical")["passed"])
 def test_hard_gate_overrides_five_point_score(self):
  issue=stable_issue("hard",Path("/tmp/a.mp4"),{},"info",.1,blocking=True)
  result=score_issues([issue],"utility");self.assertGreater(result["score"],4.9);self.assertFalse(result["passed"])
 def test_e18r_regression_fixture_maps_production_failures(self):
  d=tempfile.TemporaryDirectory();p=Path(d.name)/'e18r.wav'
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes(b'\xe8\x03'*8000*165)
  fixture=Path(__file__).parent/'fixtures/e18r_regression_ci.json'
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","run_regression_ci":False,"evidence_inputs":{"regression_ci_json":str(fixture)}})
  rules=[x["rule_id"] for x in r["issues"]]
  self.assertIn("video.asl_redline",rules);self.assertIn("video.too_many_long_shots",rules);self.assertIn("video.under1_ratio",rules)
  self.assertGreaterEqual(rules.count("audio.long_silence"),2);self.assertGreaterEqual(rules.count("audio.rms_jump"),1);self.assertGreaterEqual(r["summary"]["raw_issue_count"],r["summary"]["deduped_issue_count"])
  self.assertEqual(r["capabilities"]["action"]["status"],"NOT_RUN");self.assertEqual(r["capabilities"]["audio_analysis"]["status"],"FAIL");self.assertEqual(r["capabilities"]["regression_ci"]["status"],"FAIL");self.assertEqual(r["status"],"FAIL");d.cleanup()
 def test_audio_reports_all_rms_jumps(self):
  import struct
  d=tempfile.TemporaryDirectory();p=Path(d.name)/"jumps.wav";rate=8000
  chunks=[]
  for amp in (200,8000,200,8000): chunks.extend([amp]*rate)
  with wave.open(str(p),"wb") as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(rate);w.writeframes(struct.pack('<'+'h'*len(chunks),*chunks))
  r=Reviewer().review({"path":str(p),"kind":"audio"});raw=[x for x in r["issues"] if x["rule_id"]=="audio.rms_window_delta_raw"];self.assertEqual(len(raw),1);self.assertGreaterEqual(raw[0]["details"]["raw_count"],3);self.assertFalse(raw[0]["actionable"]);self.assertEqual(raw[0]["severity"],"info");self.assertEqual(r["scoring"]["score"],5.0);d.cleanup()
 def test_materialized_boundary_uses_short_decoded_final_windows_and_motivated_jump_is_info(self):
  import struct
  d=tempfile.TemporaryDirectory();p=Path(d.name)/'boundary.wav';rate=8000;samples=[200]*rate+[8000]*rate
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(rate);w.writeframes(struct.pack('<'+'h'*len(samples),*samples))
  mapped={'clips':[{'kind':'video','clip_id':'a','timeline_range':{'start_seconds':0,'end_seconds':1}},{'kind':'video','clip_id':'b','timeline_range':{'start_seconds':1,'end_seconds':2}}]}
  issues=Reviewer()._audio(p,{},2,mapped);jump=next(x for x in issues if x['rule_id']=='audio.rms_jump');self.assertEqual(jump['severity'],'info');self.assertFalse(jump['actionable']);self.assertEqual(jump['details']['measurement_scope'],'DECODED_FINAL_REAL_MATERIALIZED_BOUNDARY');self.assertAlmostEqual(jump['location']['cut_seconds'],1);self.assertGreater(jump['details']['local_jump_db'],12);self.assertEqual(jump['details']['continuity_adjudication']['status'],'PASS');self.assertEqual(score_issues(issues)['score'],5.0);d.cleanup()
 def test_materialized_boundary_with_real_digital_zero_remains_actionable_warning(self):
  import struct
  d=tempfile.TemporaryDirectory();p=Path(d.name)/'digital-zero.wav';rate=8000;samples=[8000]*rate+[0]*rate
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(rate);w.writeframes(struct.pack('<'+'h'*len(samples),*samples))
  mapped={'clips':[{'kind':'video','timeline_range':{'start_seconds':0,'end_seconds':1}},{'kind':'video','timeline_range':{'start_seconds':1,'end_seconds':2}}]};issues=Reviewer()._audio(p,{},2,mapped);jump=next(x for x in issues if x['rule_id']=='audio.rms_jump');self.assertEqual(jump['severity'],'warning');self.assertTrue(jump['actionable']);self.assertTrue(jump['details']['continuity_adjudication']['checks']['digital_zero']);d.cleanup()
 def test_image_without_ocr_is_not_run_and_warn(self):
  import base64
  d=tempfile.TemporaryDirectory();p=Path(d.name)/"x.png";p.write_bytes(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='))
  r=Reviewer().review({"path":str(p),"kind":"image"});self.assertEqual(r["capabilities"]["ocr"]["status"],"PASS");self.assertEqual(r["status"],"PASS");self.assertEqual(r["capabilities"]["image_analysis"]["status"],"CAPABILITY_FAIL");self.assertEqual(r["scoring"]["score"],5.0);self.assertEqual(r["capabilities"]["asr"]["status"],"NOT_APPLICABLE");d.cleanup()
 def test_png_media_probe_does_not_require_ffprobe(self):
  import base64
  d=tempfile.TemporaryDirectory();p=Path(d.name)/"x.png";p.write_bytes(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));info=probe_image(p);self.assertTrue(info["available"]);self.assertNotIn("error",info);self.assertEqual(info["streams"][0]["width"],1);reviewer=Reviewer();reviewer.ffprobe=None;r=reviewer.review({"path":str(p),"kind":"image"});self.assertEqual(r["capabilities"]["media_probe"]["status"],"PASS");d.cleanup()
 def test_not_final_repair_includes_warnings(self):
  d,p=self.wav(False);r=Reviewer().review({"path":str(p),"kind":"audio","metadata":{"status":"NOT_FINAL"},"required_capabilities":["asr"]});t=repair_task(r);self.assertTrue(t["include_warnings"]);self.assertGreater(len(t["repairs"]),0);d.cleanup()
 def test_review_id_changes_with_threshold_config(self):
  d,p=self.wav(False);rev=Reviewer();a=rev.review({"path":str(p),"kind":"audio"});b=rev.review({"path":str(p),"kind":"audio","audio_thresholds":{"max_adjacent_rms_jump_db":20}});self.assertNotEqual(a["review_id"],b["review_id"]);d.cleanup()
 def test_status_reports_live_jobs(self):
  agent=Agent(Reviewer());agent.jobs["running"]={"id":"running","method":"review","state":"running","progress":.25};z=agent.handle({"id":"s","method":"status"})["result"];self.assertEqual(z["active_jobs"],1);self.assertEqual(z["jobs"][0]["progress"],.25)
 def test_audio_default_capability_matrix_has_no_visual_penalty(self):
  d,p=self.wav(False);r=Reviewer().review({"path":str(p),"kind":"audio"});self.assertEqual(r["status"],"PASS");self.assertEqual(r["scoring"]["score"],5.0);self.assertEqual(r["capabilities"]["ocr"]["status"],"NOT_APPLICABLE");self.assertEqual(r["capabilities"]["asr"]["requirement"],"OPTIONAL");d.cleanup()
 def test_final_video_default_and_production_required_matrix(self):
  d,p=self.wav(False);fixture=Path(__file__).parent/'fixtures/e18r_regression_ci.json';r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","evidence_inputs":{"regression_ci_json":str(fixture)}});self.assertEqual(r["capabilities"]["regression_ci"]["requirement"],"REQUIRED");self.assertEqual(r["capabilities"]["action"]["requirement"],"REQUIRED");self.assertEqual(r["capabilities"]["coverage"]["requirement"],"OPTIONAL");self.assertFalse(any(x["rule_id"]=="capability.coverage.not_run" for x in r["issues"]));self.assertEqual(r["status"],"FAIL");d.cleanup()
 def test_stale_asr_sentence_ocr_and_regression_provenance_are_errors(self):
  d,p=self.wav(False); stale=Path(d.name)/"v3.mp4";stale.write_bytes(b"old"); evidence={}
  for key,field in (("asr","video"),("sentence_audit","source_final_mp4"),("ocr","video_path"),("regression_ci_json","video")):
   ref=Path(d.name)/(key+".json");ref.write_text(json.dumps({field:str(stale),"status":"PASS"}));evidence[key]=str(ref)
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":evidence})
  for cap in ("asr","sentence_audit","ocr","regression_ci"):
   self.assertEqual(r["capabilities"][cap]["status"],"ERROR");self.assertEqual(r["capabilities"][cap]["error_code"],"STALE_EVIDENCE")
  mismatch=[x for x in r["issues"] if x["rule_id"].startswith("evidence.provenance_mismatch")];self.assertEqual(len(mismatch),4);self.assertEqual(r["evidence_provenance"]["status"],"MISMATCH");self.assertEqual(r["status"],"FAIL");d.cleanup()
 def test_matching_provenance_is_not_stale(self):
  d,p=self.wav(False);ref=Path(d.name)/"asr.json";ref.write_text(json.dumps({"video":str(p),"segments":[]}));r=Reviewer().review({"path":str(p),"kind":"audio","evidence_inputs":{"asr":str(ref)}});self.assertFalse(any(x["rule_id"].startswith("evidence.provenance_mismatch") for x in r["issues"]));self.assertEqual(r["evidence_provenance"]["status"],"PASS");d.cleanup()
 def test_agentcut_time_mapping_uses_clip_metadata(self):
  d,p=self.wav(False);fixture=Path(__file__).parent/'fixtures/e18r_regression_ci.json';project=Path(d.name)/"project.json"
  project.write_text(json.dumps({"version":"1.0","timeline":{"videoTracks":[{"id":"v","clips":[{"id":"clip-1","source":"other.mp4","start":0,"duration":60,"metadata":{"dialogue_id":"DIA-001","beat_id":"B01"}}]}],"audioTracks":[]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"metadata":{"status":"NOT_FINAL"},"evidence_inputs":{"regression_ci_json":str(fixture),"agentcut_project":str(project)}});task=repair_task(r);mapped=[x for x in task["repairs"] if x["time_range"]["start_seconds"] is not None and x["time_range"]["start_seconds"]<60];self.assertTrue(mapped);self.assertEqual(mapped[0]["clip_id"],"clip-1");self.assertEqual(mapped[0]["clip_metadata"]["dialogue_id"],"DIA-001");d.cleanup()
 def test_hundred_overlapping_jumps_cluster_and_cap(self):
  p=Path('/tmp/overlap.mp4');raw=[]
  for i in range(100): raw.append(stable_issue('audio.rms_jump',p,{"start_seconds":i*.1,"end_seconds":i*.1+1},'warning',.8,blocking=False,details={"jump_db":12+i,"source_adapter":"builtin_audio"}))
  production=stable_issue('audio.rms_jump',p,{"start_seconds":4,"end_seconds":6},'warning',.99,blocking=False,details={"jump_db":20,"source_adapter":"production_regression"});raw.append(production)
  deduped=deduplicate_issues(raw);self.assertEqual(len(deduped),1);self.assertEqual(deduped[0]["details"]["deduplication"]["raw_count"],101);self.assertEqual(deduped[0]["issue_id"],production["issue_id"])
  scored=score_issues(deduped);self.assertLessEqual(scored["deduction_cap"]["audio.rms_jump"]["applied_total"],1.0);self.assertGreater(scored["score"],1.0)
 def test_long_silence_builtin_and_regression_merge(self):
  p=Path('/tmp/silence.mp4');a=stable_issue('audio.long_silence',p,{"start_seconds":115,"end_seconds":116.5},'error',.94,blocking=True,details={"source_adapter":"builtin_audio"});b=stable_issue('audio.long_silence',p,{"start_seconds":114.6325,"end_seconds":116.899563},'error',.99,blocking=True,details={"source_adapter":"production_regression"});result=deduplicate_issues([a,b]);self.assertEqual(len(result),1);self.assertEqual(result[0]["issue_id"],b["issue_id"]);self.assertEqual(result[0]["details"]["deduplication"]["raw_count"],2)
 def test_repair_task_unwraps_single_and_batches_multiple(self):
  d,p=self.wav();report=Reviewer().review({"path":str(p),"kind":"audio"});single=repair_task({"items":[report]});self.assertEqual(single["source_review_id"],report["review_id"]);batch=repair_task({"items":[report,report]});self.assertEqual(batch["schema"],"qingshan.agentcut.repair_task_batch.v1");self.assertEqual(len(batch["tasks"]),2);d.cleanup()
 def test_repair_task_cli_schema_error_has_no_traceback(self):
  d=tempfile.TemporaryDirectory();p=Path(d.name)/"bad.json";p.write_text('{"items":[]}');out=io.StringIO()
  with contextlib.redirect_stdout(out): code=cli_main(["repair-task",str(p)])
  payload=json.loads(out.getvalue());self.assertEqual(code,2);self.assertFalse(payload["ok"]);self.assertEqual(payload["error"]["type"],"SchemaError");d.cleanup()
 def test_v5_long_shots_expand_to_intersecting_agentcut_clips(self):
  d,p=self.wav(False);fixture=Path(__file__).parent/'fixtures/e18r_v5_long_shots.json';project=Path(d.name)/'project.json'
  project.write_text(json.dumps({"version":"1.0","timeline":{"videoTracks":[{"id":"v","clips":[{"id":"c1","source":"a.mp4","start":0,"duration":5,"metadata":{"beat_id":"B1"}},{"id":"c2","source":"b.mp4","start":5,"duration":8,"metadata":{"beat_id":"B2"}},{"id":"c3","source":"c.mp4","start":13,"duration":17,"metadata":{"beat_id":"B3"}}]}],"audioTracks":[]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture),"agentcut_project":str(project)}});issue=next(x for x in r["issues"] if x["rule_id"]=="video.motivated_long_shots");self.assertEqual(len(issue["details"]["long_shots"]),1);self.assertEqual(issue["details"]["long_shots"][0]["start_seconds"],18);self.assertFalse(issue["details"]["long_shots"][0]["static_hold"]);self.assertTrue(issue["details"]["long_shots"][0]["motivated"]);self.assertFalse(issue["details"]["long_shots"][0]["static_hold_blocking"])
  self.assertFalse(any(x["rule_id"]=="video.too_many_long_shots" for x in r["issues"]));self.assertEqual(r["summary"]["raw_long_shot_count"],1);self.assertEqual(r["summary"]["motivated_long_shot_count"],1);self.assertEqual(r["summary"]["unmotivated_long_shot_count"],0);task=repair_task(r);self.assertFalse(any(x.get("aggregate_rule_id")=="video.too_many_long_shots" for x in task["repairs"]));d.cleanup()
 def test_unmotivated_long_shots_over_limit_still_block_and_expand(self):
  d,p=self.wav(False);source=json.loads((Path(__file__).parent/'fixtures/e18r_v5_long_shots.json').read_text())
  for row in source["static_hold_gate"]["shot_rows"]:row["has_speech"]=False;row["status"]="FAIL"
  fixture=Path(d.name)/'unmotivated.json';fixture.write_text(json.dumps(source));r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture)}});issue=next(x for x in r["issues"] if x["rule_id"]=="video.too_many_long_shots");self.assertTrue(issue["blocking"]);self.assertEqual(issue["details"]["unmotivated_long_shot_count"],3);self.assertGreaterEqual(r["summary"]["blocking_count"],1);d.cleanup()
 def test_repair_preserves_rule_id(self):
  d,p=self.wav();r=Reviewer().review({"path":str(p),"kind":"audio"});task=repair_task(r);self.assertTrue(task["repairs"]);self.assertTrue(all(x.get("rule_id") for x in task["repairs"]));d.cleanup()
 def test_non_actionable_info_has_zero_deduction(self):
  issue=stable_issue('video.motivated_long_shots',Path('/tmp/a.mp4'),{},'info',1,blocking=False,details={"actionable":False});score=score_issues([issue]);self.assertEqual(score["score"],5.0);self.assertEqual(score["deductions"][0]["amount"],0)
 def test_audio_cut_continuity_distinguishes_dynamics_and_dropout(self):
  rate=1000;continuous=[1000 if i<1000 else 8000 for i in range(2000)];self.assertEqual(adjudicate_audio_cut(continuous,rate,1)["status"],"PASS")
  dropout=[1000]*900+[0]*200+[1000]*900;result=adjudicate_audio_cut(dropout,rate,1);self.assertEqual(result["status"],"FAIL");self.assertTrue(result["checks"]["dropout"])
 def test_v10_visual_shot_rms_shape_becomes_motivated_info(self):
  import math,struct
  d=tempfile.TemporaryDirectory();p=Path(d.name)/'v10.wav';rate=8000;samples=[]
  for second in range(11):
   amp=1000 if second%2==0 else 9000
   samples.extend(int(amp*math.sin(2*math.pi*220*i/rate)) for i in range(rate))
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(rate);w.writeframes(struct.pack('<'+'h'*len(samples),*samples))
  fixture=Path(__file__).parent/'fixtures/e18r_v10_rms_shape.json';r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture)}});jumps=[x for x in r["issues"] if x["rule_id"]=='audio.rms_jump'];self.assertEqual(len(jumps),1);self.assertEqual(jumps[0]["severity"],'info');self.assertFalse(jumps[0]["actionable"]);self.assertEqual(jumps[0]["details"]["deduplication"]["raw_count"],10);self.assertEqual(jumps[0]["details"]["continuity_adjudication"]["status"],'PASS');self.assertEqual(r["capabilities"]["audio_analysis"]["status"],"PASS");self.assertEqual(r["capabilities"]["audio_analysis"]["raw_status"],"FAIL");self.assertEqual(r["capabilities"]["regression_ci"]["status"],"WARN");self.assertEqual(r["capabilities"]["regression_ci"]["raw_status"],"FAIL");self.assertIn('scene_brightness',r["capabilities"]["regression_ci"]["required_capability_gaps"]);self.assertFalse(any(x.get('rule_id')=='audio.rms_jump' for x in repair_task(r)['repairs']));d.cleanup()
 def test_concurrent_review_findings_are_deterministic_and_ordered(self):
  d,p=self.wav(False);items=[{"path":str(p),"kind":"audio","clip_id":"a"},{"path":str(p),"kind":"audio","clip_id":"b"}];rev=Reviewer(workers=2);first=rev.review_many(items);second=rev.review_many(items);self.assertEqual([x["agentcut"]["clip_id"] for x in first],["a","b"]);self.assertEqual([x["review_id"] for x in first],[x["review_id"] for x in second]);self.assertEqual([x["issues"] for x in first],[x["issues"] for x in second]);d.cleanup()
 def test_audio_capability_alias_normalizes_without_false_gap(self):
  d,p=self.wav(False);r=Reviewer().review({"path":str(p),"kind":"audio","required_capabilities":["audio"]});self.assertEqual(r["capabilities"]["audio_analysis"]["status"],"PASS");self.assertEqual(r["capabilities"]["audio_analysis"]["requirement"],"REQUIRED");self.assertNotIn("audio",r["capabilities"]);self.assertFalse(any(x["rule_id"]=="capability.audio.not_run" for x in r["issues"]));self.assertEqual(r["config_summary"]["capability_aliases"],{"audio":"audio_analysis"});d.cleanup()
 def test_voice_registration_evidence_can_be_explicitly_required(self):
  d,p=self.wav(False);evidence={}
  for key in ("asr","sentence_audit","voiceprint"):
   ref=Path(d.name)/(key+'.json');ref.write_text(json.dumps({"status":"PASS","media_path":str(p)}));evidence[key]=str(ref)
  r=Reviewer().review({"path":str(p),"kind":"audio","required_capabilities":["audio","asr","sentence_audit","voiceprint"],"evidence_inputs":evidence})
  for cap in ("audio_analysis","asr","sentence_audit","voiceprint"):self.assertEqual(r["capabilities"][cap]["requirement"],"REQUIRED");self.assertEqual(r["capabilities"][cap]["status"],"PASS")
  self.assertFalse(any(x["rule_id"].startswith("capability.") for x in r["issues"]));d.cleanup()
 def test_required_voice_evidence_missing_is_not_silently_optional(self):
  d,p=self.wav(False);r=Reviewer().review({"path":str(p),"kind":"audio","required_capabilities":["asr","sentence_audit","voiceprint"]})
  for cap in ("asr","sentence_audit","voiceprint"):self.assertEqual(r["capabilities"][cap]["requirement"],"REQUIRED");self.assertEqual(r["capabilities"][cap]["status"],"NOT_RUN")
  self.assertEqual(sum(x["rule_id"].startswith("capability.") for x in r["issues"]),3);d.cleanup()
 def test_agentcut_dialogue_motivates_long_shot_without_asr(self):
  d,p=self.wav(False);fixture=Path(d.name)/'regression.json';project=Path(d.name)/'project.json'
  fixture.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":8,"thresholds":{"redline_asl":99,"max_single_shot":6,"max_unmotivated_long_shots":0,"under1_min":0,"under1_max":1,"static_hold_motion_max":1.5,"static_hold_seconds_max":4},"asl":{"mean":8,"durations":[8],"cut_times":[8],"under_1s_ratio":0},"static_hold_gate":{"shot_rows":[{"shot_index":1,"mean_motion":0,"has_speech":False,"status":"FAIL_STATIC_HOLD"}]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"opening_10s_speech_energy":{"opening_speech_segment_count":0},"failures":["opening_10s_speech_energy_fail"]}))
  project.write_text(json.dumps({"version":"1.0","expectedDialogueIds":["DIA-001"],"requireBurnedSubtitles":True,"timeline":{"videoTracks":[{"id":"v","clips":[{"id":"v1","source":"a.mp4","start":0,"duration":8,"metadata":{}}]}],"audioTracks":[{"id":"a","clips":[{"id":"a1","source":"a.wav","start":0,"duration":8,"metadata":{"dialogue_id":"DIA-001"}}]}],"subtitleTracks":[{"id":"s","clips":[{"id":"s1","dialogue_id":"DIA-001","start":0,"duration":8,"text":"对白"}]}]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture),"agentcut_project":str(project)}});issue=next(x for x in r["issues"] if x["rule_id"]=="video.motivated_long_shots");row=issue["details"]["long_shots"][0];self.assertTrue(row["has_speech"]);self.assertEqual(row["motivation_reason"],"agentcut_dialogue_or_subtitle");self.assertEqual(row["speech_evidence"]["dialogue_ids"],["DIA-001"]);self.assertFalse(any(x["rule_id"]=="video.too_many_long_shots" for x in r["issues"]));opening=next(x for x in r["issues"] if x["rule_id"]=="audio.opening_speech_energy_reconciled");self.assertFalse(opening["blocking"]);self.assertFalse(opening["actionable"]);d.cleanup()
 def test_agentcut_cuts_reconcile_false_static_hold_and_supply_coverage(self):
  d,p=self.wav(False);fixture=Path(d.name)/'regression.json';project=Path(d.name)/'project.json'
  fixture.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":14,"thresholds":{"redline_asl":99,"max_single_shot":6,"max_unmotivated_long_shots":0,"under1_min":0,"under1_max":1,"static_hold_motion_max":1.5,"static_hold_seconds_max":4},"asl":{"mean":14,"durations":[14],"cut_times":[14],"under_1s_ratio":0},"static_hold_gate":{"shot_rows":[{"shot_index":1,"mean_motion":0,"has_speech":False,"status":"FAIL_STATIC_HOLD"}]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"manifest_shot_reconciliation":{"status":"NOT_REQUESTED"},"failures":["unmotivated_static_hold:1:0+14:motion=0.000"]}))
  video=[{"id":f"v{i}","source":f"v{i}.mp4","start":i*2,"duration":2,"metadata":{}} for i in range(7)];audio=[{"id":"a1","source":"a.wav","start":0,"duration":14,"metadata":{"dialogue_id":"DIA-001"}}];subs=[{"id":"s1","dialogue_id":"DIA-001","start":0,"duration":14,"text":"对白"}]
  project.write_text(json.dumps({"version":"1.0","expectedDialogueIds":["DIA-001"],"requireBurnedSubtitles":True,"timeline":{"videoTracks":[{"id":"v","clips":video}],"audioTracks":[{"id":"a","clips":audio}],"subtitleTracks":[{"id":"s","clips":subs}]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","required_capabilities":["coverage_manifest"],"use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture),"agentcut_project":str(project)}});self.assertEqual(r["capabilities"]["coverage"]["status"],"PASS");self.assertEqual(r["capabilities"]["coverage"]["requirement"],"REQUIRED");self.assertNotIn("coverage_manifest",r["capabilities"]);self.assertFalse(any(x["rule_id"] in {"video.too_many_long_shots","video.static_hold"} for x in r["issues"]));reconciled=next(x for x in r["issues"] if x["rule_id"]=="video.static_hold_reconciled");self.assertFalse(reconciled["actionable"]);self.assertEqual(len(reconciled["details"]["segments"]),7);self.assertEqual(r["config_summary"]["capability_aliases"],{"coverage_manifest":"coverage"});d.cleanup()
 def test_agentcut_materialized_short_cuts_override_low_scene_detector_ratio(self):
  d,p=self.wav(False);fixture=Path(d.name)/'regression.json';project=Path(d.name)/'project.json'
  durations=[.8]*8+[2.0]*64;clips=[];start=0
  for i,duration in enumerate(durations):clips.append({"id":f"c{i}","source":f"source-{i}.mp4","start":start,"duration":duration,"metadata":{}});start+=duration
  fixture.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":start,"thresholds":{"redline_asl":999,"max_single_shot":999,"max_unmotivated_long_shots":99,"under1_min":.05,"under1_max":.15},"asl":{"segment_count":53,"mean":3,"durations":[2]*51+[.8,.8],"cut_times":[],"under_1s":2,"under_1s_ratio":2/53},"static_hold_gate":{"shot_rows":[]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"failures":["under1_ratio_out_of_range:0.04"]}))
  project.write_text(json.dumps({"version":"1.0","output":{"path":str(p)},"timeline":{"videoTracks":[{"id":"v","clips":clips}],"audioTracks":[],"subtitleTracks":[]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture),"agentcut_project":str(project)}});self.assertFalse(any(x["rule_id"]=="video.under1_ratio" for x in r["issues"]));issue=next(x for x in r["issues"] if x["rule_id"]=="video.under1_ratio_reconciled");self.assertFalse(issue["blocking"]);self.assertFalse(issue["actionable"]);self.assertEqual(issue["details"]["detector"]["segment_count"],53);self.assertEqual(issue["details"]["agentcut_project"]["clip_count"],72);self.assertEqual(issue["details"]["agentcut_project"]["validated_under_1s_count"],8);self.assertAlmostEqual(issue["details"]["agentcut_project"]["under_1s_ratio"],8/72);self.assertEqual(r["agentcut"]["pacing"]["overlap_count"],0);d.cleanup()
 def test_agentcut_short_cut_overlap_cannot_override_detector_failure(self):
  d,p=self.wav(False);fixture=Path(d.name)/'regression.json';project=Path(d.name)/'project.json'
  fixture.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":4,"thresholds":{"redline_asl":99,"max_single_shot":99,"max_unmotivated_long_shots":99,"under1_min":.05,"under1_max":.15},"asl":{"segment_count":2,"mean":2,"durations":[2,2],"cut_times":[],"under_1s":0,"under_1s_ratio":0},"static_hold_gate":{"shot_rows":[]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"failures":["under1_ratio_out_of_range:0.00"]}))
  clips=[{"id":"a","source":"a.mp4","start":0,"duration":2,"metadata":{}},{"id":"fake","source":"b.mp4","start":1.5,"duration":.8,"metadata":{}},{"id":"c","source":"c.mp4","start":2.3,"duration":1.7,"metadata":{}}];project.write_text(json.dumps({"version":"1.0","output":{"path":str(p)},"timeline":{"videoTracks":[{"id":"v","clips":clips}],"audioTracks":[]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"regression_ci_json":str(fixture),"agentcut_project":str(project)}});issue=next(x for x in r["issues"] if x["rule_id"]=="video.under1_ratio");self.assertTrue(issue["blocking"]);self.assertEqual(issue["details"]["agentcut_project"]["overlap_count"],1);self.assertEqual(issue["details"]["agentcut_project"]["validated_under_1s_count"],0);d.cleanup()
 def test_agentcut_muxed_derivative_lineage_accepts_same_version_not_cross_version(self):
  d,p=self.wav(False);media=Path(d.name)/'E19R_AGENTCUT_TRIAL_V9_MUXED_SUBTITLED_NOT_FINAL.wav';p.rename(media);project=Path(d.name)/'project.json';timeline={"videoTracks":[{"id":"v","clips":[{"id":"c","source":"c.mp4","start":0,"duration":1,"metadata":{}}]}],"audioTracks":[]}
  project.write_text(json.dumps({"version":"1.0","output":{"path":str(Path(d.name)/'E19R_AGENTCUT_TRIAL_V9_SHORT_CUTS_GAIN_SUBTITLED_NOT_FINAL.mp4')},"timeline":timeline}));r=Reviewer().review({"path":str(media),"kind":"audio","evidence_inputs":{"agentcut_project":str(project)}});check=next(x for x in r["evidence_provenance"]["checks"] if x["evidence_key"]=="agentcut_project");self.assertEqual(check["status"],"MATCH");self.assertEqual(check["lineage"]["method"],"version_identity_and_timeline_duration");self.assertEqual(r["capabilities"]["agentcut_project"]["status"],"PASS")
  project.write_text(json.dumps({"version":"1.0","output":{"path":str(Path(d.name)/'E19R_AGENTCUT_TRIAL_V8_SHORT_CUTS_GAIN_SUBTITLED_NOT_FINAL.mp4')},"timeline":timeline}));stale=Reviewer().review({"path":str(media),"kind":"audio","evidence_inputs":{"agentcut_project":str(project)}});self.assertEqual(stale["capabilities"]["agentcut_project"]["status"],"ERROR");self.assertTrue(any(x["rule_id"]=="evidence.provenance_mismatch.agentcut_project" for x in stale["issues"]));d.cleanup()
 def test_explicit_action_and_brightness_pass_override_regression_missing(self):
  d,p=self.wav(False);reg=Path(d.name)/'reg.json';action=Path(d.name)/'action.json';brightness=Path(d.name)/'brightness.json'
  reg.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":1,"thresholds":{"redline_asl":99,"max_single_shot":99,"under1_min":0,"under1_max":1},"asl":{"mean":1,"durations":[1],"under_1s_ratio":0},"static_hold_gate":{"shot_rows":[]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"action_realtime":{"status":"MISSING"},"scene_brightness":{"status":"MISSING"},"failures":["action_realtime_evidence_missing","scene_brightness_audit_missing"]}));action.write_text(json.dumps({"status":"PASS","media_path":str(p),"failures":[]}));brightness.write_text(json.dumps({"source_final_mp4":str(p),"timeline_order_verified":True,"shots":[{"shot_id":"s1","mean_luma":50}]}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"required_capabilities":["action","scene_brightness"],"evidence_inputs":{"regression_ci_json":str(reg),"action_audit":str(action),"scene_brightness":str(brightness)}});self.assertEqual(r["capabilities"]["action"]["status"],"PASS");self.assertEqual(r["capabilities"]["scene_brightness"]["status"],"PASS");self.assertEqual(r["capabilities"]["scene_brightness"]["derived_status"],"PASS_DERIVED");self.assertEqual(r["capabilities"]["regression_ci"]["status"],"WARN");self.assertIn('black_frame_analysis',r["capabilities"]["regression_ci"]["required_capability_gaps"]);self.assertFalse(any(x["rule_id"] in {"capability.action.not_run","capability.scene_brightness.not_run"} for x in r["issues"]));d.cleanup()
 def test_stereo_4063_fixture_uses_frame_duration_and_never_emits_out_of_range_issue(self):
  import array
  d=tempfile.TemporaryDirectory();p=Path(d.name)/'stereo-4.063.wav';rate=44100;frames=179178;interleaved=array.array('h')
  for i in range(frames):
   amp=300 if i<rate*2 else 9000;interleaved.extend((amp,-amp//2))
  with wave.open(str(p),'wb') as w:w.setnchannels(2);w.setsampwidth(2);w.setframerate(rate);w.writeframes(interleaved.tobytes())
  pcm_rate,samples=audio_pcm(p,None);self.assertEqual(pcm_rate,rate);self.assertEqual(len(samples),frames);r=Reviewer().review({"path":str(p),"kind":"audio"});duration=frames/rate;self.assertEqual(r["validity"],"VALID");self.assertEqual(r["summary"]["invalid_time_range_count"],0)
  for issue in r["issues"]:
   loc=issue.get("location",{});self.assertGreaterEqual(loc.get("start_seconds",0),0);self.assertLessEqual(loc.get("end_seconds",duration),duration+1e-9)
  d.cleanup()
 def test_invalid_adapter_time_range_is_clamped_marked_invalid_and_not_scored(self):
  issue=stable_issue('audio.rms_jump',Path('/tmp/a.wav'),{"start_seconds":5,"end_seconds":6},'warning',1,blocking=False);invalid=sanitize_issue_time_ranges([issue],4.063);self.assertEqual(len(invalid),1);self.assertEqual(issue['location']['start_seconds'],4.063);self.assertEqual(issue['location']['end_seconds'],4.063);self.assertFalse(issue['actionable']);self.assertEqual(score_issues([issue])['score'],5.0)
 def test_audited_gate_policy_can_override_episode_runtime_and_under1_defaults(self):
  d,p=self.wav(False);fixture=Path(d.name)/'reg.json';source={"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":144,"thresholds":{"min_runtime":150,"max_runtime":180,"redline_asl":99,"max_single_shot":99,"under1_min":.05,"under1_max":.15},"asl":{"mean":3,"durations":[3]*48,"under_1s_ratio":.03},"static_hold_gate":{"shot_rows":[]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"failures":["runtime_too_short:144","under1_ratio_out_of_range:0.03"]};fixture.write_text(json.dumps(source))
  default=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"metadata":{"episode":"E18R"},"evidence_inputs":{"regression_ci_json":str(fixture)}});self.assertTrue(any(x['rule_id']=='video.runtime_min' for x in default['issues']));self.assertTrue(any(x['rule_id']=='video.under1_ratio' for x in default['issues']))
  policy={"version":"e18r.v11.runtime-pacing.v1","reason":"E18R V11 approved 144s episode-specific delivery profile","episode":"E18R","overrides":{"min_runtime":140,"under1_min":.02}};adjusted=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"metadata":{"episode":"E18R"},"gate_policy":policy,"evidence_inputs":{"regression_ci_json":str(fixture)}});self.assertFalse(any(x['rule_id'] in {'video.runtime_min','video.under1_ratio'} for x in adjusted['issues']));self.assertTrue(adjusted['config_summary']['gate_policy']['applied']);self.assertEqual(adjusted['config_summary']['gate_policy']['version'],policy['version']);d.cleanup()
 def test_gate_policy_without_audit_fields_is_rejected(self):
  d,p=self.wav(False);result=Reviewer().validate({"items":[{"path":str(p),"kind":"audio","gate_policy":{"overrides":{"min_runtime":140}}}]});self.assertFalse(result['valid']);self.assertTrue(any('version is required' in x for x in result['errors']));d.cleanup()
 def test_episode_authoritative_anti_padding_reconciles_runtime_and_pacing_but_preserves_raw(self):
  d,p=self.wav(False);reg=Path(d.name)/'reg.json';project=Path(d.name)/'project.json';contract=Path(d.name)/'anti-padding.json'
  contract.write_text(json.dumps({"schema":"qingshan.agentcut_anti_padding_contract.v1","episode":"E20","status":"ACTIVE_HARD_GATE","machine_gate":{"shorter_runtime_allowed_when_coverage_is_complete":True,"padding_forbidden":True}}))
  durations=[1.5,2.0,2.5,2.0];clips=[];start=0
  for i,duration in enumerate(durations):clips.append({"id":f"DIA-{i+1:03d}-VIDEO","source":f"source-{i}.mp4","start":start,"duration":duration,"metadata":{"dialogue_id":f"DIA-{i+1:03d}"}});start+=duration
  audio=[{"id":f"DIA-{i+1:03d}-AUDIO","source":f"source-{i}.mp4","start":sum(durations[:i]),"duration":duration} for i,duration in enumerate(durations)]
  project.write_text(json.dumps({"version":"1.0","runtimePolicy":{"allowShorter":True,"paddingForbidden":True,"onCoverageGap":"fail"},"metadata":{"episode":"E20","anti_padding_contract":str(contract)},"output":{"path":str(p)},"timeline":{"videoTracks":[{"id":"v","clips":clips}],"audioTracks":[{"id":"a","clips":audio}]}}))
  reg.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":start,"thresholds":{"min_runtime":150,"max_runtime":180,"redline_asl":5,"max_single_shot":6,"max_unmotivated_long_shots":2,"under1_min":.05,"under1_max":.15},"asl":{"segment_count":2,"mean":4,"durations":[4,4],"cut_times":[4],"under_1s":0,"under_1s_ratio":0},"static_hold_gate":{"shot_rows":[]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"frame_repeat":{"max_nonadjacent_repeat_cluster":4},"failures":["runtime_out_of_range:8.00","asl_above_threshold:4.00","under1_ratio_out_of_range:0.00","repeated_frame_cluster:4"]}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"metadata":{"episode":"E20"},"evidence_inputs":{"regression_ci_json":str(reg),"agentcut_project":str(project)}})
  rules={x['rule_id']:x for x in r['issues']};self.assertNotIn('video.runtime_min',rules);self.assertNotIn('video.under1_ratio',rules);self.assertIn('video.runtime_min_reconciled',rules);self.assertIn('video.pacing_reconciled',rules)
  pacing=rules['video.pacing_reconciled'];self.assertFalse(pacing['blocking']);self.assertFalse(pacing['actionable']);self.assertTrue(pacing['details']['raw_failures_preserved']);self.assertIn('repeated_frame_cluster:4',pacing['details']['detector']['raw_failures']);self.assertEqual(pacing['details']['agentcut_project']['clip_count'],4);self.assertTrue(r['agentcut']['pacing']['mean_seconds']>0);d.cleanup()
 def test_anti_padding_is_not_authoritative_when_coverage_is_incomplete(self):
  d,p=self.wav(False);reg=Path(d.name)/'reg.json';project=Path(d.name)/'project.json';contract=Path(d.name)/'contract.json'
  contract.write_text(json.dumps({"schema":"qingshan.agentcut_anti_padding_contract.v1","episode":"E20","status":"ACTIVE_HARD_GATE","machine_gate":{"shorter_runtime_allowed_when_coverage_is_complete":True,"padding_forbidden":True}}));reg.write_text(json.dumps({"schema":"qingshan.regression_ci.v1","status":"FAIL","runtime_seconds":8,"thresholds":{"min_runtime":150,"redline_asl":99,"max_single_shot":99,"under1_min":0,"under1_max":1},"asl":{"mean":8,"durations":[8],"under_1s_ratio":0},"static_hold_gate":{"shot_rows":[]},"audio_bed_continuity":{"status":"PASS","shot_rows":[],"unmotivated_silence_segments":[],"excessive_adjacent_rms_jumps":[]},"failures":["runtime_out_of_range:8"]}));project.write_text(json.dumps({"version":"1.0","runtimePolicy":{"allowShorter":True,"paddingForbidden":True},"metadata":{"episode":"E20","anti_padding_contract":str(contract)},"output":{"path":str(p)},"expectedDialogueIds":["DIA-001"],"timeline":{"videoTracks":[{"id":"v","clips":[{"id":"v","source":"v.mp4","start":0,"duration":8,"metadata":{"dialogue_id":"DIA-001"}}]}],"audioTracks":[]}}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"metadata":{"episode":"E20"},"evidence_inputs":{"regression_ci_json":str(reg),"agentcut_project":str(project)}});self.assertTrue(any(x['rule_id']=='video.runtime_min' and x['blocking'] for x in r['issues']));self.assertEqual(r['agentcut']['pacing']['clip_count'],1);d.cleanup()
 def test_ambience_gain_and_short_periodic_loop_are_production_blockers(self):
  d,p=self.wav(False);amb=Path(d.name)/'ambience.wav';amb.write_bytes(p.read_bytes());project=Path(d.name)/'project.json';clips=[]
  for i in range(8):clips.append({"id":f'amb-{i}',"source":str(amb),"start":i*4,"duration":4,"volume":2.0,"transitionIn":{"type":"fade","duration":.04},"transitionOut":{"type":"fade","duration":.04},"metadata":{"kind":"NIGHT_AMBIENCE","speech_free":True}})
  project.write_text(json.dumps({"version":"1.0","timeline":{"videoTracks":[],"audioTracks":[{"id":"AMBIENCE","clips":clips}]}}));r=Reviewer().review({"path":str(p),"kind":"video","scope":"asset","use_existing_tools":False,"evidence_inputs":{"agentcut_project":str(project)}});rules={x['rule_id']:x for x in r['issues']};self.assertTrue(rules['audio.ambience_gain_excessive']['blocking']);self.assertTrue(rules['audio.periodic_ambience_loop']['blocking']);self.assertEqual(r['capabilities']['ambience_analysis']['status'],'FAIL');self.assertEqual(r['capabilities']['ambience_analysis']['ambience_clip_count'],8);self.assertEqual(rules['audio.periodic_ambience_loop']['details']['repeat_count'],8);self.assertEqual(rules['audio.periodic_ambience_loop']['details']['minimum_crossfade_seconds'],.04);d.cleanup()
 def test_safe_non_repeating_ambience_passes_dedicated_gate(self):
  d,p=self.wav(True);project=Path(d.name)/'project.json';project.write_text(json.dumps({"version":"1.0","timeline":{"videoTracks":[],"audioTracks":[{"id":"AMBIENCE","clips":[{"id":"amb","source":str(p),"start":0,"duration":30,"volume":.5,"transitionIn":{"type":"fade","duration":.5},"transitionOut":{"type":"fade","duration":.5},"metadata":{"kind":"AMBIENCE","speech_free":True}}]}]}}));r=Reviewer().review({"path":str(p),"kind":"video","scope":"asset","use_existing_tools":False,"evidence_inputs":{"agentcut_project":str(project)}});self.assertEqual(r['capabilities']['ambience_analysis']['status'],'PASS');self.assertFalse(any(x['rule_id'].startswith('audio.ambience_') or x['rule_id']=='audio.periodic_ambience_loop' for x in r['issues']));d.cleanup()

 def test_ocr_uses_exact_three_second_outro_boundary_and_flags_native_duplicate(self):
  d,p=self.wav(False);project=Path(d.name)/'project.json';ocr=Path(d.name)/'ocr.json'
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes(b'\xe8\x03'*80000)
  project.write_text(json.dumps({"version":"1.0","output":{"path":str(p)},"outro":{"enabled":True,"duration":3,"brandText":"NALU MOTION"},"timeline":{"videoTracks":[{"id":"v","clips":[{"id":"main","source":"main.mp4","start":0,"duration":7,"metadata":{}}]}],"audioTracks":[],"subtitleTracks":[{"id":"s","clips":[{"id":"cap","start":6,"duration":1,"text":"跟我走，别踩药架。"}]}]}}))
  ocr.write_text(json.dumps({"schema":"qingshan.final_video_ocr_audit.v2","source_final_mp4":str(p),"agentcut_project":str(project),"review_end_seconds":7,"sample_interval_seconds":.1,"recognitions":[{"time":6.2,"text":"跟我走","confidence":.97},{"time":8.5,"text":"NALU MOTION","confidence":.99}]}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"agentcut_project":str(project),"ocr":str(ocr)}});issue=next(x for x in r['issues'] if x['rule_id']=='video.readable_native_text_duplicate');self.assertAlmostEqual(issue['location']['start_seconds'],6.2);self.assertTrue(issue['blocking']);self.assertEqual(r['capabilities']['ocr']['review_window']['main_content_end_seconds'],7);self.assertEqual(r['capabilities']['ocr']['review_window']['boundary_source'],'materialized_main_video_timeline_end');self.assertEqual(r['capabilities']['ocr']['allowed_branding'][0]['text'],'NALU MOTION');d.cleanup()
 def test_ocr_rejects_fixed_tail_that_excludes_main_content(self):
  d,p=self.wav(False);project=Path(d.name)/'project.json';ocr=Path(d.name)/'ocr.json'
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes(b'\xe8\x03'*80000)
  project.write_text(json.dumps({"version":"1.0","output":{"path":str(p)},"outro":{"enabled":True,"duration":3},"timeline":{"videoTracks":[{"id":"v","clips":[{"id":"main","source":"main.mp4","start":0,"duration":7,"metadata":{}}]}],"audioTracks":[]}}));ocr.write_text(json.dumps({"source_final_mp4":str(p),"exclusion_start_seconds":6,"recognitions":[]}))
  r=Reviewer().review({"path":str(p),"kind":"video","scope":"final","use_existing_tools":False,"evidence_inputs":{"agentcut_project":str(project),"ocr":str(ocr)}});gap=next(x for x in r['issues'] if x['rule_id']=='ocr.main_content_coverage_gap');self.assertEqual(gap['location'],{'start_seconds':6.0,'end_seconds':7.0});self.assertEqual(r['capabilities']['ocr']['status'],'ERROR');self.assertFalse(r['capabilities']['ocr']['review_window']['blind_tail_exclusion']);d.cleanup()
 def test_ocr_without_trusted_outro_requires_media_end_and_allows_known_brand(self):
  d,p=self.wav(False);ocr=Path(d.name)/'ocr.json';ocr.write_text(json.dumps({"schema":"qingshan.final_video_ocr_audit.v2","source_final_mp4":str(p),"sampled_through_seconds":1,"recognitions":[{"time":.9,"text":"NALU MOTION","confidence":.9}]}));r=Reviewer().review({"path":str(p),"kind":"video","scope":"asset","use_existing_tools":False,"evidence_inputs":{"ocr":str(ocr)}});self.assertEqual(r['capabilities']['ocr']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['review_window']['boundary_source'],'media_end_no_trusted_outro_manifest');self.assertFalse(any(x['rule_id'].startswith('ocr.') or x['rule_id'].startswith('video.readable_native_text') for x in r['issues']));d.cleanup()
 def test_ocr_normalized_pass_rejects_isolated_symbol_and_number_hallucinations(self):
  d,p=self.wav(False);ocr=Path(d.name)/'ocr.json';ocr.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v2','source_final_mp4':str(p),'status':'PASS','sampled_through_seconds':1,'sample_interval_seconds':.5,'lexicon_policy_configured':True,'critical_text_failures':0,'latin_chars':0,'unlisted_chinese_hits':[],'numeric_string_hits':[],'recognitions':[{'time_seconds':.1,'text':'®','confidence':.79,'forbidden':False,'forbidden_tokens':[]},{'time_seconds':.5,'text':'3','confidence':.54,'numeric_string':False},{'time_seconds':.9,'text':'37','confidence':.54,'numeric_string':True}]}))
  r=Reviewer().review({'path':str(p),'kind':'video','scope':'asset','use_existing_tools':False,'evidence_inputs':{'ocr':str(ocr)}});cap=r['capabilities']['ocr'];self.assertEqual(cap['status'],'PASS');self.assertEqual(cap['derived_status'],'PASS_NORMALIZED_AUTHORITATIVE');self.assertEqual(cap['raw_recognition_count'],3);self.assertEqual(cap['raw_rejected_count'],3);self.assertEqual(cap['main_content_hit_count'],0);self.assertFalse(any(x['rule_id'].startswith('video.readable_native_text') for x in r['issues']));d.cleanup()
 def test_ocr_persistent_actual_text_still_blocks_without_authoritative_clean_decision(self):
  d,p=self.wav(False);ocr=Path(d.name)/'ocr.json';ocr.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v2','source_final_mp4':str(p),'status':'UNKNOWN','sampled_through_seconds':1,'sample_interval_seconds':.5,'confidence_threshold':.5,'recognitions':[{'time_seconds':.2,'text':'药铺','confidence':.7},{'time_seconds':.7,'text':'药铺','confidence':.72}]}))
  r=Reviewer().review({'path':str(p),'kind':'video','scope':'asset','use_existing_tools':False,'evidence_inputs':{'ocr':str(ocr)}});hits=[x for x in r['issues'] if x['rule_id']=='video.readable_native_text'];self.assertTrue(hits);self.assertTrue(all(x['blocking'] for x in hits));self.assertEqual(r['capabilities']['ocr']['status'],'FAIL');d.cleanup()
 def test_ocr_explicit_forbidden_text_blocks_even_single_low_confidence_hit(self):
  d,p=self.wav(False);ocr=Path(d.name)/'ocr.json';ocr.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v2','source_final_mp4':str(p),'status':'FAIL','sampled_through_seconds':1,'sample_interval_seconds':.5,'recognitions':[{'time_seconds':.4,'text':'禁显','confidence':.6,'forbidden':True,'forbidden_tokens':['禁显']}]}))
  r=Reviewer().review({'path':str(p),'kind':'video','scope':'asset','use_existing_tools':False,'evidence_inputs':{'ocr':str(ocr)}});hit=next(x for x in r['issues'] if x['rule_id']=='video.readable_native_text');self.assertTrue(hit['blocking']);self.assertEqual(r['capabilities']['ocr']['status'],'FAIL');d.cleanup()
 def test_ocr_raw_fail_is_reassessed_with_character_persistence_and_subtitle_policy(self):
  d,p=self.wav(False);ocr=Path(d.name)/'ocr.json';rows=[
   {'time_seconds':.05,'text':'办','confidence':.92,'allowed':False,'forbidden':False,'unlisted_chinese':False},
   {'time_seconds':.15,'text':'办','confidence':.9,'allowed':False,'forbidden':False,'unlisted_chinese':False},
   {'time_seconds':.25,'text':'D','confidence':.63,'latin_chars':1,'unlisted_chinese':False},
   {'time_seconds':.35,'text':'D','confidence':.53,'latin_chars':1,'unlisted_chinese':False},
   {'time_seconds':.45,'text':'4800','confidence':.82,'numeric_string':True,'unlisted_chinese':False},
   {'time_seconds':.55,'text':'e','confidence':.61,'latin_chars':1,'unlisted_chinese':False},
   {'time_seconds':.65,'text':'国区','confidence':.69,'unlisted_chinese':True},
   {'time_seconds':.75,'text':' intended subtitle ','confidence':.99,'classification':'INTENDED_SUBTITLE'}]
  ocr.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v2','source_final_mp4':str(p),'status':'FAIL','sampled_through_seconds':1,'sample_interval_seconds':.1,'lexicon_policy_configured':True,'critical_text_failures':5,'latin_chars':4,'unlisted_chinese_hits':[],'numeric_string_hits':[],'recognitions':rows}))
  r=Reviewer().review({'path':str(p),'kind':'video','scope':'asset','use_existing_tools':False,'evidence_inputs':{'ocr':str(ocr)}});cap=r['capabilities']['ocr'];self.assertEqual(cap['status'],'PASS');self.assertEqual(cap['raw_status'],'FAIL');self.assertEqual(cap['derived_status'],'PASS_POLICY_NORMALIZED_RAW_FAIL');self.assertEqual(cap['evidence_policy']['critical_text_failures_raw'],5);self.assertEqual(cap['raw_recognition_count'],8);self.assertEqual(cap['raw_rejected_count'],8);self.assertFalse(any(x['rule_id'].startswith('video.readable_native_text') for x in r['issues']));d.cleanup()
 def test_fullcut_exact_sha_raw_fail_and_machine_adjudication_pass(self):
  import hashlib
  d,p=self.wav(False);raw=Path(d.name)/'raw.json';visual=Path(d.name)/'contact.jpg';visual.write_bytes(b'frames');adj=Path(d.name)/'adj.json';digest=hashlib.sha256(p.read_bytes()).hexdigest();raw.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v4','source_final_mp4':str(p),'status':'FAIL','sampled_through_seconds':1,'sample_interval_seconds':.5,'sample_count':2,'critical_text_failures':0,'recognitions':[{'time_seconds':.5,'text':'6000','confidence':.92,'numeric_string':True}]}));adj.write_text(json.dumps({'schema':'qingshan.fullcut-ocr-machine-adjudication.v1','candidate':str(p),'candidate_sha256':digest,'status':'PASS_MACHINE_ADJUDICATION','raw_ocr_report':str(raw),'raw_ocr_report_sha256':hashlib.sha256(raw.read_bytes()).hexdigest(),'raw_report_preserved':True,'critical_text_failures':0,'visual_evidence':str(visual),'visual_evidence_sha256':hashlib.sha256(visual.read_bytes()).hexdigest(),'confidence':.98,'platform_mutation_authorized':False}));r=Reviewer().review({'path':str(p),'kind':'video','scope':'full_cut','use_existing_tools':False,'required_capabilities':['ocr'],'evidence_inputs':{'ocr_raw':str(raw),'ocr_adjudication':str(adj)}});cap=r['capabilities']['ocr'];self.assertEqual(cap['status'],'PASS');self.assertEqual(cap['raw_status'],'FAIL');self.assertEqual(cap['derived_status'],'PASS_MACHINE_ADJUDICATED_EXACT_FRAMES');self.assertTrue(cap['machine_adjudication']['valid']);self.assertEqual(cap['raw_rejected_recognitions'][0]['reason'],'EXACT_FRAME_MACHINE_ADJUDICATION');self.assertNotIn('ocr',r['required_capability_failures']);d.cleanup()
 def test_fullcut_machine_adjudication_sha_mismatch_cannot_pass(self):
  import hashlib
  d,p=self.wav(False);raw=Path(d.name)/'raw.json';visual=Path(d.name)/'contact.jpg';visual.write_bytes(b'frames');adj=Path(d.name)/'adj.json';raw.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v4','source_final_mp4':str(p),'status':'FAIL','sampled_through_seconds':1,'critical_text_failures':0,'recognitions':[]}));adj.write_text(json.dumps({'schema':'qingshan.fullcut-ocr-machine-adjudication.v1','candidate':str(p),'candidate_sha256':'0'*64,'status':'PASS_MACHINE_ADJUDICATION','raw_ocr_report':str(raw),'raw_ocr_report_sha256':hashlib.sha256(raw.read_bytes()).hexdigest(),'raw_report_preserved':True,'critical_text_failures':0,'visual_evidence':str(visual),'visual_evidence_sha256':hashlib.sha256(visual.read_bytes()).hexdigest(),'confidence':.98,'platform_mutation_authorized':False}));r=Reviewer().review({'path':str(p),'kind':'video','scope':'full_cut','use_existing_tools':False,'required_capabilities':['ocr'],'evidence_inputs':{'ocr_raw':str(raw),'ocr_adjudication':str(adj)}});cap=r['capabilities']['ocr'];self.assertEqual(cap['status'],'FAIL');self.assertFalse(cap['machine_adjudication']['valid']);self.assertIn('candidate_sha256',cap['machine_adjudication']['errors']);d.cleanup()
 def test_fullcut_ocr_coverage_gap_is_scanned_and_not_blindly_adjudicated(self):
  import hashlib
  from unittest.mock import patch
  d,p=self.wav(False);raw=Path(d.name)/'raw.json';visual=Path(d.name)/'contact.jpg';visual.write_bytes(b'frames');adj=Path(d.name)/'adj.json';digest=hashlib.sha256(p.read_bytes()).hexdigest();raw.write_text(json.dumps({'schema':'qingshan.final_video_ocr_audit.v4','source_final_mp4':str(p),'status':'FAIL','sampled_through_seconds':.5,'sample_interval_seconds':.5,'critical_text_failures':0,'recognitions':[]}));adj.write_text(json.dumps({'schema':'qingshan.fullcut-ocr-machine-adjudication.v1','candidate':str(p),'candidate_sha256':digest,'status':'PASS_MACHINE_ADJUDICATION','raw_ocr_report':str(raw),'raw_ocr_report_sha256':hashlib.sha256(raw.read_bytes()).hexdigest(),'raw_report_preserved':True,'critical_text_failures':0,'visual_evidence':str(visual),'visual_evidence_sha256':hashlib.sha256(visual.read_bytes()).hexdigest(),'confidence':.98,'platform_mutation_authorized':False}));gap={'status':'PASS','candidate_sha256':digest,'sample_count':1,'engine':'test','recognitions':[{'time_seconds':.75,'text':'真实文字','confidence':.99}]}
  with patch.object(Reviewer,'_run_video_ocr_gap',return_value=(gap,None)):r=Reviewer().review({'path':str(p),'kind':'video','scope':'full_cut','required_capabilities':['ocr'],'evidence_inputs':{'ocr_raw':str(raw),'ocr_adjudication':str(adj)}})
  self.assertEqual(r['capabilities']['ocr']['supplemental_gap_scan']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['status'],'FAIL');self.assertTrue(any(x['rule_id']=='video.readable_native_text' for x in r['issues']));d.cleanup()
 def test_benign_regression_end_rounding_is_clamped_without_invalid_report(self):
  issue=stable_issue('audio.rms_jump',Path('/tmp/a.mp4'),{'start_seconds':176.333333,'end_seconds':181.71},'info',1,blocking=False,details={'actionable':False});invalid=sanitize_issue_time_ranges([issue],181.708333);self.assertEqual(invalid,[]);self.assertEqual(issue['location']['end_seconds'],181.708333);self.assertEqual(issue['details']['time_range_sanitization']['status'],'BENIGN_BOUNDARY_ROUNDING_CLAMPED');self.assertFalse(issue['blocking'])
 def test_ocr_pass_adjudicated_accepts_nested_audit_scope_main_end(self):
  d,p=self.wav(False);project=Path(d.name)/'project.json';ocr=Path(d.name)/'ocr.json'
  with wave.open(str(p),'wb') as w:w.setnchannels(1);w.setsampwidth(2);w.setframerate(8000);w.writeframes(b'\xe8\x03'*80000)
  project.write_text(json.dumps({'version':'1.0','output':{'path':str(p)},'outro':{'enabled':True,'duration':3},'timeline':{'videoTracks':[{'id':'v','clips':[{'id':'main','source':'main.mp4','start':0,'duration':7}]}],'audioTracks':[]}}));ocr.write_text(json.dumps({'schema':'qingshan.ocr_machine_adjudication.v1','source_final_mp4':str(p),'status':'PASS_ADJUDICATED','audit_scope':{'main_content_end':7,'outro_start':7,'fixed_tail_blind_exclusion':False},'readable_unintended_text_count':0,'watermark_count':0}))
  r=Reviewer().review({'path':str(p),'kind':'video','scope':'asset','use_existing_tools':False,'evidence_inputs':{'agentcut_project':str(project),'ocr':str(ocr)}});self.assertEqual(r['capabilities']['ocr']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['review_window']['declared_review_end_seconds'],7);self.assertFalse(any(x['rule_id']=='ocr.main_content_coverage_gap' for x in r['issues']));d.cleanup()
 def test_derived_action_lineage_accepts_current_video_plus_matching_decoded_md5(self):
  d,p=self.wav(False);stale=Path(d.name)/'old.wav';stale.write_bytes(p.read_bytes());action=Path(d.name)/'action.json';identity='78c1d4218c5fcdd7a28e240bffb38e02';action.write_text(json.dumps({'schema':'qingshan.action_realtime_audit.v1','status':'PASS','media_path':str(stale),'video':str(p),'derived_from':{'decoded_video_md5':identity}}));r=Reviewer().review({'path':str(p),'kind':'audio','required_capabilities':['action'],'metadata':{'decoded_video_md5':identity},'evidence_inputs':{'action_audit':str(action)}});self.assertEqual(r['capabilities']['action']['status'],'PASS');check=next(x for x in r['evidence_provenance']['checks'] if x['evidence_key']=='action_audit');self.assertEqual(check['status'],'MATCH_DERIVED_DECODED_VIDEO_IDENTITY');self.assertEqual(check['lineage']['method'],'current_media_reference_and_decoded_video_md5');d.cleanup()
 def test_derived_action_wrong_decoded_md5_remains_stale(self):
  d,p=self.wav(False);stale=Path(d.name)/'old.wav';stale.write_bytes(p.read_bytes());action=Path(d.name)/'action.json';action.write_text(json.dumps({'status':'PASS','media_path':str(stale),'video':str(p),'derived_from':{'decoded_video_md5':'wrong'}}));r=Reviewer().review({'path':str(p),'kind':'audio','metadata':{'decoded_video_md5':'expected'},'evidence_inputs':{'action_audit':str(action)}});self.assertEqual(r['capabilities']['action']['status'],'ERROR');self.assertTrue(any(x['rule_id']=='evidence.provenance_mismatch.action' for x in r['issues']));d.cleanup()
 def test_story_duration_plans_4_5_6_8_15_seconds_pass(self):
  reviewer=Reviewer();path=Path('/tmp/seedance.mp4')
  for planned in (4,5,6,8,15):
   issues,cap=reviewer._story_duration(path,{'task':{'source_id':f's-{planned}','duration_plan':{'policy':'qingshan.shot_generation_duration.v1','duration_seconds':planned}}},planned+.19);self.assertEqual(issues,[]);self.assertEqual(cap['status'],'PASS');self.assertTrue(cap['passed']);self.assertAlmostEqual(cap['delta_seconds'],.19);self.assertEqual(cap['policy_version'],'qingshan.shot_generation_duration.v1')
 def test_story_duration_missing_out_of_range_and_mismatch_block(self):
  reviewer=Reviewer();path=Path('/tmp/seedance.mp4');cases=[({'task':{'source_id':'missing'}},5,'video.duration_plan_missing'),({'task':{'duration_plan':{'duration_seconds':16}}},16,'video.duration_plan_out_of_range'),({'task':{'duration_plan':{'duration_seconds':8}}},7.79,'video.duration_plan_mismatch')]
  for item,actual,rule in cases:
   issues,cap=reviewer._story_duration(path,item,actual);self.assertEqual(cap['status'],'FAIL');self.assertFalse(cap['passed']);self.assertEqual(issues[0]['rule_id'],rule);self.assertTrue(issues[0]['blocking']);self.assertTrue(issues[0]['decision']['rollback_allowed']);self.assertIn('planned_duration_seconds',issues[0]['details']);self.assertIn('actual_duration_seconds',issues[0]['details']);self.assertIn('delta_seconds',issues[0]['details'])
 def test_story_duration_configurable_encoding_tolerance(self):
  reviewer=Reviewer();path=Path('/tmp/seedance.mp4');item={'duration_tolerance_seconds':.3,'task':{'duration_plan':{'duration_seconds':5}}};issues,cap=reviewer._story_duration(path,item,5.25);self.assertEqual(issues,[]);self.assertEqual(cap['encoding_tolerance_seconds'],.3)
 def test_review_many_report_preserves_passes_and_retries_only_failures(self):
  class Stub(Reviewer):
   def review(self,item):return {'review_id':'REV-'+item['id'],'status':item['result']}
  reviewer=Stub(workers=4);items=[{'id':'PASS1','path':'a','result':'PASS'},{'id':'FAIL1','path':'b','result':'FAIL'},{'id':'WARN1','path':'c','result':'WARN'}];result=reviewer.review_many_report(items);self.assertEqual(result['summary'],{'total':3,'passed':2,'failed':1,'capability_failed':0,'content_failed':1,'workers':4});self.assertEqual(result['status'],'CONTENT_FAIL');self.assertEqual([x['review_id'] for x in result['items']],['REV-PASS1','REV-FAIL1','REV-WARN1']);self.assertEqual([x['index'] for x in result['retry_items']],[1]);self.assertEqual(result['retry_policy'],'FAILED_ITEMS_ONLY')
 def test_review_many_internal_zero_of_two_fail_is_top_level_content_fail_and_cli_nonzero(self):
  import contextlib,io
  from unittest.mock import patch
  from qingshan_review import cli
  d=tempfile.TemporaryDirectory();request=Path(d.name)/'request.json';request.write_text(json.dumps({'items':[{'path':'a'},{'path':'b'}]}));payload={'schema':'qingshan.review_many.result.v2','status':'CONTENT_FAIL','content_status':'CONTENT_FAIL','summary':{'total':2,'passed':0,'failed':2},'failed_items':[{'index':0},{'index':1}]}
  output=io.StringIO()
  with patch.object(Reviewer,'review_many_report',return_value=payload),contextlib.redirect_stdout(output):rc=cli.main(['review-many',str(request)])
  parsed=json.loads(output.getvalue());self.assertEqual(rc,1);self.assertEqual(parsed['status'],'CONTENT_FAIL');self.assertEqual(parsed['summary']['passed'],0);self.assertEqual(len(parsed['failed_items']),2);d.cleanup()
 def test_storyboard_visual_adjudication_binds_exact_sha_and_unifies_image_ocr(self):
  import base64
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'sheet.png';media.write_bytes(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));qa=root/'qa/e26_storyboard_sheet_test';qa.mkdir(parents=True);checks={x:'PASS' for x in ('six_column_layout','six_visual_rows','intentional_composition_difference','identity_and_location_continuity','no_text_inside_visual_panels','setup_impact_tableau','close_to_wide_scale_jump','environmental_power_visualization')};evidence=qa/'E26_STORYBOARD_SHEET_AI_VISUAL_ADJUDICATION.json';evidence.write_text(json.dumps({'schema':'qingshan.storyboard_sheet_ai_visual_adjudication.v1','episode':'E26','status':'PASS','confidence':.96,'evidence':[{'sheet_kind':'fight_sheet','path':str(media),'sha256':__import__('hashlib').sha256(media.read_bytes()).hexdigest(),'row_count':6,'composition_sequence':['a','b','c','d','e','f'],'checks':checks}],'failures':[],'rollback':'keep source'}))
  r=Reviewer(production_root=str(root)).review({'path':str(media),'kind':'image','scope':'sequence','importance':'critical','pass_score':4.5,'required_capabilities':['image_analysis','ocr'],'metadata':{'episode':'E26','sheet_kind':'fight_sheet'}});self.assertEqual(r['status'],'PASS');self.assertEqual(r['capabilities']['image_analysis']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['review_scope'],'VISUAL_PANELS_ONLY');self.assertEqual(r['scoring']['score'],5.0);d.cleanup()
 def test_storyboard_missing_required_semantic_check_is_capability_fail_not_content_fail(self):
  import base64,hashlib
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'sheet.png';media.write_bytes(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));qa=root/'qa/e27_storyboard_sheet_test';qa.mkdir(parents=True);checks={x:'PASS' for x in ('six_column_layout','six_visual_rows','intentional_composition_difference','no_text_inside_visual_panels','setup_impact_tableau','close_to_wide_scale_jump','environmental_power_visualization')};(qa/'E27_STORYBOARD_SHEET_AI_VISUAL_ADJUDICATION.json').write_text(json.dumps({'schema':'qingshan.storyboard_sheet_ai_visual_adjudication.v1','episode':'E27','status':'PASS','confidence':.96,'evidence':[{'sheet_kind':'fight_sheet','sha256':hashlib.sha256(media.read_bytes()).hexdigest(),'checks':checks}]}))
  item={'path':str(media),'kind':'image','scope':'sequence','required_capabilities':['image_analysis','ocr'],'metadata':{'episode':'E27','sheet_kind':'fight_sheet'}};r=Reviewer(production_root=str(root)).review(item);self.assertEqual(r['status'],'CAPABILITY_FAIL');self.assertEqual(r['content_status'],'CAPABILITY_FAIL');self.assertEqual(r['capabilities']['image_analysis']['status'],'CAPABILITY_FAIL');self.assertEqual(r['summary']['blocking_count'],0);batch=Reviewer(production_root=str(root)).review_many_report([item]);self.assertEqual(batch['status'],'CAPABILITY_FAIL');self.assertEqual(batch['summary']['capability_failed'],1);d.cleanup()
 def test_keyframe_visual_and_still_ocr_bind_exact_sha(self):
  import base64,hashlib
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'keyframe.png';media.write_bytes(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));checks={x:'PASS' for x in ('canonical_identity_continuity','scene_authority','story_action_clarity','no_text_or_pseudotext','no_extra_or_duplicated_bodies','native_anatomy')};visual=root/'visual.json';visual.write_text(json.dumps({'schema':'qingshan.image_visual_adjudication.v1','episode':'E28','status':'PASS','confidence':.97,'evidence':[{'source_id':'B01','sha256':hashlib.sha256(media.read_bytes()).hexdigest(),'checks':checks}],'rollback':'keep source'}));ocr=root/'ocr.json';ocr.write_text(json.dumps({'schema':'qingshan.still_image_ocr_audit.v1','source_images':[str(media)],'status':'PASS','critical_text_failures':0,'recognitions':[]}));item={'path':str(media),'kind':'image','scope':'shot','required_capabilities':['image_analysis','ocr'],'metadata':{'episode':'E28','source_id':'B01'},'evidence_inputs':{'image_visual':str(visual),'ocr':str(ocr)}};r=Reviewer(production_root=str(root)).review(item);self.assertEqual(r['status'],'PASS');self.assertEqual(r['capabilities']['image_analysis']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['status'],'PASS');self.assertEqual(r['capabilities']['ocr']['review_scope'],'FULL_RESOLUTION_KEYFRAME');self.assertEqual(r['capabilities']['visual_continuity']['status'],'PASS');d.cleanup()
 def test_keyframe_visual_rejects_sha_mismatch_without_content_fail(self):
  import base64
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'keyframe.png';media.write_bytes(base64.b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));visual=root/'visual.json';visual.write_text(json.dumps({'schema':'qingshan.image_visual_adjudication.v1','episode':'E28','status':'PASS','confidence':.97,'evidence':[{'source_id':'B01','sha256':'0'*64,'checks':{}}]}));item={'path':str(media),'kind':'image','scope':'shot','required_capabilities':['image_analysis'],'metadata':{'episode':'E28','source_id':'B01'},'evidence_inputs':{'image_visual':str(visual)}};r=Reviewer(production_root=str(root)).review(item);self.assertEqual(r['status'],'CAPABILITY_FAIL');self.assertEqual(r['capabilities']['image_analysis']['status'],'CAPABILITY_FAIL');self.assertEqual(r['summary']['blocking_count'],0);d.cleanup()
 def test_e20_dia006_periodic_first_fails_and_r3_passes(self):
  base=Path('/Users/rogerwu/qingshan_short_drama/qa/e20_story_duration_correction_v2_20260718');first=base/'DIA-006_AI_REVIEW.json';r3=base/'E20_DIA006_CADENCE_R3_AI_REVIEW.json'
  if not first.is_file() or not r3.is_file():self.skipTest('read-only E20 production fixtures unavailable')
  first_media=Path(json.loads(first.read_text())['video']);r3_media=Path(json.loads(r3.read_text())['video']);reviewer=Reviewer();first_issues,_,_=reviewer._video_external(first_media,{'evidence_inputs':{'cadence_audit':str(first)}},5.06);r3_issues,_,_=reviewer._video_external(r3_media,{'evidence_inputs':{'cadence_audit':str(r3)}},5.06);periodic=next(x for x in first_issues if x['rule_id']=='video.periodic_duplicate');self.assertTrue(periodic['blocking']);self.assertEqual(periodic['location']['start_frame'],19);self.assertEqual(periodic['location']['end_frame'],63);self.assertFalse(any(x['rule_id']=='video.periodic_duplicate' for x in r3_issues))
 def test_black_frame_scan_outputs_frame_time_and_pblack_blocker(self):
  from unittest.mock import patch
  import subprocess
  stderr='[Parsed_blackframe_0] frame:17 pblack:100 pts:11333 t:0.708313 type:I last_keyframe:17\nframe=   48 fps=0.0\n'
  reviewer=Reviewer();reviewer.ffmpeg='/fake/ffmpeg'
  with patch('qingshan_review.core.subprocess.run',return_value=subprocess.CompletedProcess([],0,'',stderr)):
   issues,cap=reviewer._black_frame_scan(Path('/tmp/x.mp4'),{},2.0)
  self.assertEqual(cap['status'],'FAIL');self.assertEqual(cap['decoded_frame_count'],48);self.assertEqual(cap['detected_black_frame_count'],1);self.assertEqual(issues[0]['location']['frame'],17);self.assertEqual(issues[0]['evidence'][0]['pblack'],100);self.assertAlmostEqual(issues[0]['location']['start_seconds'],.708313);self.assertTrue(issues[0]['blocking'])
 def test_black_frame_zero_scan_passes(self):
  from unittest.mock import patch
  import subprocess
  reviewer=Reviewer();reviewer.ffmpeg='/fake/ffmpeg'
  with patch('qingshan_review.core.subprocess.run',return_value=subprocess.CompletedProcess([],0,'','')):
   issues,cap=reviewer._black_frame_scan(Path('/tmp/x.mp4'),{},2.0)
  self.assertEqual(issues,[]);self.assertEqual(cap['status'],'PASS');self.assertEqual(cap['frames'],[])
 def test_legacy_agentcut_audio_clip_ids_restore_dialogue_order_and_coverage(self):
  d=tempfile.TemporaryDirectory();project=Path(d.name)/'project.json';media=Path(d.name)/'x.mp4';media.write_bytes(b'x');video=[{'id':'v1','source':'a','start':0,'duration':1,'metadata':{'dialogue_id':'DIA-001'}},{'id':'v2','source':'b','start':1,'duration':1,'metadata':{'dialogue_id':'DIA-022'}}];audio=[{'id':'E20-DIA-001-AUDIO','source':'a.wav','start':0,'duration':1},{'id':'E20-B01-MOTIVATED-COVERAGE-AUDIO','source':'bed.wav','start':.5,'duration':1},{'id':'E20-DIA-022-AUDIO','source':'b.wav','start':1,'duration':1}];project.write_text(json.dumps({'version':'1.0','timeline':{'videoTracks':[{'id':'v','clips':video}],'audioTracks':[{'id':'mixed','clips':audio}]}}));mapped=Reviewer()._agentcut_map(media,{'evidence_inputs':{'agentcut_project':str(project)}});self.assertEqual(mapped['coverage']['expected_dialogue_order'],['DIA-001','DIA-022']);self.assertEqual(mapped['coverage']['audio_dialogue_order'],['DIA-001','DIA-022']);self.assertEqual(mapped['coverage']['legacy_clip_id_mapped_count'],2);self.assertTrue(mapped['coverage']['complete']);d.cleanup()
 def test_zero_sentence_pass_evidence_becomes_blocking_fail(self):
  d,p=self.wav(False);e=Path(d.name)/'sentence.json';e.write_text(json.dumps({'status':'PASS','media_path':str(p),'sentence_count':0,'sentences':[]}));r=Reviewer().review({'path':str(p),'kind':'audio','required_capabilities':['sentence_audit'],'evidence_inputs':{'sentence_audit':str(e)}});self.assertEqual(r['capabilities']['sentence_audit']['status'],'FAIL');issue=next(x for x in r['issues'] if x['rule_id']=='audio.dialogue_zero_sentence_false_pass');self.assertTrue(issue['blocking']);d.cleanup()
 def test_brightness_jump_requires_complete_high_confidence_adjudication(self):
  d=tempfile.TemporaryDirectory();media=Path(d.name)/'x.mp4';media.write_bytes(b'x');e=Path(d.name)/'brightness.json';e.write_text(json.dumps({'shots':[{'shot_id':'a','start':0,'end':1,'end_luma':20},{'shot_id':'b','start':1,'end':2,'start_luma':60}]}));issues,cap=Reviewer()._brightness_evidence(media,str(e));self.assertEqual(cap['status'],'FAIL');self.assertEqual(cap['raw_jump_count'],1);self.assertTrue(issues[0]['blocking']);self.assertEqual(issues[0]['details']['raw_jump_luma'],40);d.cleanup()
 def test_brightness_jump_pass_with_adjudication_preserves_raw_jump(self):
  d=tempfile.TemporaryDirectory();media=Path(d.name)/'x.mp4';media.write_bytes(b'x');proof=Path(d.name)/'contact.jpg';proof.write_bytes(b'proof');e=Path(d.name)/'brightness.json';e.write_text(json.dumps({'shots':[{'shot_id':'a','start':0,'end':1,'end_luma':20},{'shot_id':'b','start':1,'end':2,'start_luma':60}],'adjudications':[{'left_shot_id':'a','right_shot_id':'b','evidence_file':str(proof),'reason':'motivated lantern reveal','confidence':.95,'raw_jump_preserved':True}]}));issues,cap=Reviewer()._brightness_evidence(media,str(e));self.assertEqual(issues,[]);self.assertEqual(cap['status'],'PASS');self.assertEqual(cap['raw_status'],'PASS_WITH_ADJUDICATION');self.assertEqual(cap['raw_jumps'][0]['raw_jump_luma'],40);d.cleanup()
 def test_brightness_missing_evidence_is_blocking(self):
  issues,cap=Reviewer()._brightness_evidence(Path('/tmp/x.mp4'),None);self.assertEqual(cap['status'],'FAIL');self.assertEqual(issues[0]['rule_id'],'video.brightness_evidence_missing');self.assertTrue(issues[0]['blocking'])
 def test_generic_image_evidence_is_discovered_by_exact_sha_not_batch_path(self):
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'candidate.png';media.write_bytes(__import__('base64').b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));qa=root/'qa/arbitrary_writer_batch';qa.mkdir(parents=True);digest=__import__('hashlib').sha256(media.read_bytes()).hexdigest();checks={x:'PASS' for x in ('canonical_identity_continuity','scene_authority','story_action_clarity','no_text_or_pseudotext','no_extra_or_duplicated_bodies','native_anatomy')};(qa/'renamed.json').write_text(json.dumps({'schema':'qingshan.image_visual_adjudication.v1','episode':'E27','status':'PASS','confidence':.96,'evidence':[{'source_id':'E27-B01','sha256':digest,'checks':checks}]}));r=Reviewer(production_root=str(root)).review({'path':str(media),'kind':'image','scope':'shot','required_capabilities':['image_analysis','ocr'],'metadata':{'episode':'E27','source_id':'E27-B01'}});self.assertEqual(r['status'],'PASS');self.assertEqual(r['capabilities']['image_analysis']['candidate_sha256'],digest);self.assertEqual(r['capabilities']['image_analysis']['source_adapter'],'production_image_visual_adjudication');d.cleanup()
 def test_runtime_image_adapter_accepts_arbitrary_path_and_exact_sha(self):
  from unittest.mock import patch
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'never_seen_before.png';media.write_bytes(__import__('base64').b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='));adapter=root/'adapter.py';adapter.write_text("import sys,json\np=json.load(sys.stdin)\nc={x:'PASS' for x in ('canonical_identity_continuity','scene_authority','story_action_clarity','no_text_or_pseudotext','no_extra_or_duplicated_bodies','native_anatomy')}\nprint(json.dumps({'schema':'qingshan.image_visual_adjudication.v1','confidence':.97,'evidence':[{'sha256':p['candidate_sha256'],'checks':c}]}))\n")
  with patch.dict('os.environ',{'QINGSHAN_IMAGE_ANALYSIS_COMMAND':f'{__import__("sys").executable} {adapter}'}):r=Reviewer(production_root=str(root)).review({'path':str(media),'kind':'image','required_capabilities':['image_analysis','ocr'],'metadata':{'episode':'E27','source_id':'new'}})
  self.assertEqual(r['status'],'PASS');self.assertEqual(r['capabilities']['image_analysis']['source_adapter'],'runtime_image_visual');self.assertEqual(r['capabilities']['ocr']['source_adapter'],'runtime_image_visual');d.cleanup()
 def test_required_image_runtime_absence_is_capability_fail_not_content_fail(self):
  from unittest.mock import patch
  d=tempfile.TemporaryDirectory();media=Path(d.name)/'x.png';media.write_bytes(__import__('base64').b64decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='))
  with patch.dict('os.environ',{},clear=True):r=Reviewer(production_root=d.name).review({'path':str(media),'kind':'image','required_capabilities':['image_analysis','ocr']})
  self.assertEqual(r['status'],'CAPABILITY_FAIL');self.assertEqual(r['content_status'],'CAPABILITY_FAIL');self.assertEqual(r['capabilities']['image_analysis']['error_code'],'IMAGE_VISUAL_RUNTIME_UNAVAILABLE');self.assertNotEqual(r['capabilities']['ocr']['status'],'NOT_RUN');d.cleanup()
 def test_e27_n04_n09_action_near_duplicate_ratio_hard_gate(self):
  for fixture,clip,expected in [('e27_n04_action_cadence.json','E27-N04',.282407),('e27_n09_action_cadence.json','E27-N09',.484375)]:
   d=tempfile.TemporaryDirectory();media=Path(d.name)/f'{clip}.mp4';media.write_bytes(b'video');source=Path(__file__).parent/'fixtures'/fixture;data=json.loads(source.read_text());data['video']=str(media);cadence=Path(d.name)/'cadence.json';cadence.write_text(json.dumps(data));issues,cap,physics=Reviewer(production_root=d.name)._video_external(media,{'clip_id':clip,'action_required':True,'action_intensity':'high','evidence_inputs':{'cadence_audit':str(cadence)}},8.0);issue=next(x for x in issues if x['rule_id']=='video.action_near_duplicate_ratio');self.assertAlmostEqual(issue['details']['near_duplicate_ratio'],expected,6);self.assertEqual(issue['details']['threshold'],.15);self.assertEqual(issue['details']['clip_id'],clip);self.assertEqual(issue['details']['candidate_sha256'],__import__('hashlib').sha256(media.read_bytes()).hexdigest());self.assertTrue(issue['evidence'][0]['windows']);self.assertEqual(cap['status'],'FAIL');self.assertEqual(physics['status'],'CAPABILITY_FAIL');d.cleanup()
 def test_static_dialogue_shot_does_not_apply_action_ratio_threshold(self):
  d=tempfile.TemporaryDirectory();media=Path(d.name)/'dialogue.mp4';media.write_bytes(b'video');cadence=Path(d.name)/'cadence.json';cadence.write_text(json.dumps({'video':str(media),'output_fps':24,'periodic_duplicates':{'near_duplicate_ratio':.7,'near_duplicate_frame_count':3,'near_duplicate_frames':[1,2,3]}}));issues,cap,physics=Reviewer(production_root=d.name)._video_external(media,{'clip_id':'DIA-001','action_required':False,'action_intensity':'low','evidence_inputs':{'cadence_audit':str(cadence)}},4);self.assertFalse(any(x['rule_id']=='video.action_near_duplicate_ratio' for x in issues));self.assertIsNone(cap['action_near_duplicate_ratio_threshold']);self.assertIsNone(physics);d.cleanup()
 def test_action_physics_exact_sha_and_all_required_checks(self):
  d=tempfile.TemporaryDirectory();media=Path(d.name)/'fight.mp4';media.write_bytes(b'video');digest=__import__('hashlib').sha256(media.read_bytes()).hexdigest();cadence=Path(d.name)/'cadence.json';cadence.write_text(json.dumps({'video':str(media),'output_fps':24,'periodic_duplicates':{'near_duplicate_ratio':.1,'near_duplicate_frames':[]}}));checks={x:{'status':'PASS','confidence':.95} for x in ('wind_up','contact','force_transfer','result','real_hand_prop_contact','no_floating_hands','no_object_drift','complete_action_head_tail')};checks['contact']={'status':'FAIL','confidence':.94,'location':{'start_seconds':1.25,'end_seconds':1.5,'start_frame':30,'end_frame':36},'evidence':'blade misses hand'};physics=Path(d.name)/'physics.json';physics.write_text(json.dumps({'schema':'qingshan.action_physics_audit.v1','candidate_sha256':digest,'confidence':.94,'checks':checks}));issues,cap,action=Reviewer(production_root=d.name)._video_external(media,{'clip_id':'FIGHT-01','action_required':True,'evidence_inputs':{'cadence_audit':str(cadence),'action_physics':str(physics)}},4);issue=next(x for x in issues if x['rule_id']=='video.action_physics.contact');self.assertEqual(issue['location']['start_frame'],30);self.assertEqual(issue['details']['candidate_sha256'],digest);self.assertEqual(action['status'],'FAIL');self.assertEqual(action['failed_checks'],['contact']);self.assertEqual(cap['status'],'PASS');d.cleanup()

 def test_validate_accepts_full_cut_and_action_physics_contract(self):
  d,p=self.wav(False);result=Reviewer().validate({'items':[{'path':str(p),'kind':'video','scope':'full_cut','action_required':True,'action_intensity':'high','required_capabilities':['action_physics']}]});self.assertTrue(result['valid'],result);d.cleanup()

class ShotRecipeConformanceTests(unittest.TestCase):
 def official_fixture(self, stale=False):
  import hashlib
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'candidate.mp4';media.write_bytes(b'official-agentcut-candidate');sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
  sidecar=root/'candidate.mp4.shot-recipes.json';project=root/'project.json';manifest=root/'candidate.mp4.manifest.json';envelope=root/'provenance.json'
  row={'clipId':'C1','recipeId':'camera.slow_push_in','timelineTimeRange':{'start':0,'end':3},'frameRange':{'startFrame':0,'endFrameExclusive':72},'motionArc':{'phases':[{'phaseId':'setup','frameRange':{'startFrame':0,'endFrameExclusive':16}},{'phaseId':'contact','frameRange':{'startFrame':16,'endFrameExclusive':52}},{'phaseId':'result','frameRange':{'startFrame':52,'endFrameExclusive':72}}]},'plannedHold':{'windows':[{'phaseId':'result_read','frameRange':{'startFrame':59,'endFrameExclusive':72,'frameCount':13}}]},'sfxCues':[{'cueId':'primary_contact','phaseId':'contact','frame':16}],'intentionalBlack':None,'provenance':{'outputFps':24},'resolvedRecipe':{'recipe_id':'camera.slow_push_in','camera_motion':{'type':'push'},'subject_anchor':{'x_ratio':.5,'y_ratio':.4},'beat_anchor':{'phase_id':'contact'},'qa_contract':{'required_checks':['motion_arc','subject_anchor','beat_sync','sfx_cue','readability']}}}
  sidecar.write_text(json.dumps({'schema':'agentcut.materialized_shot_recipes.v1','outputSha256':sha(media),'materializedTimeline':[row]}));project.write_text(json.dumps({'version':'1.0','timeline':{'videoTracks':[]}}));manifest.write_text(json.dumps({'version':'agentcut.render-manifest.v1','shotRecipes':{'sidecarSha256':sha(sidecar)}}))
  envelope.write_text(json.dumps({'schema':'qingshan.agentcut.shot_recipe_provenance.v1','candidate_sha256':'0'*64 if stale else sha(media),'project_id':'P1','project_version':'1.0','project_sha256':sha(project),'timeline_sha256':sha(sidecar),'manifest_sha256':sha(manifest)}))
  item={'kind':'video','scope':'final','required_capabilities':list(__import__('qingshan_review.shot_recipe',fromlist=['CAPABILITIES']).CAPABILITIES),'evidence_inputs':{'agentcut_shot_recipe_sidecar':str(sidecar),'agentcut_project':str(project),'agentcut_render_manifest':str(manifest),'shot_recipe_provenance':str(envelope)}}
  return d,media,item
 def fixture(self, mutate=None, omit=(), stale=None):
  import hashlib
  d=tempfile.TemporaryDirectory();root=Path(d.name);media=root/'candidate.mp4';media.write_bytes(b'synthetic-not-final-shot-recipe-candidate');digest=hashlib.sha256(media.read_bytes()).hexdigest()
  timeline={'candidate_sha256':digest,'project_id':'P1','project_version':'V1','clips':[{'clip_id':'C1','recipe_id':'R1','fps':24,'start_frame':0,'end_frame':96,'start_seconds':0,'end_seconds':4,'actual':{'camera_motion':{'type':'push','phases':[{'phase':'enter'},{'phase':'sustain'},{'phase':'settle'}],'curve_rmse':.02},'subject_anchor':{'max_drift_px':2},'action_phases':[{'phase':'setup','end_frame':20},{'phase':'contact','end_frame':48},{'phase':'result','end_frame':72}],'result_hold_frames':24,'transition_frame':72,'sfx_peaks':[{'cue_id':'hit','frame':48,'motivated':True}],'readability':[{'element_id':'evidence','frame':84,'pixel_height':32,'readable':True}]}}]}
  recipe={'recipe_id':'R1','clip_id':'C1','camera_motion':{'type':'push','phases':[{'phase':'enter'},{'phase':'sustain'},{'phase':'settle'}],'max_curve_rmse':.05},'subject_anchor':{'target':'lead_face','tolerance_px':5},'action':{'required_phases':['setup','contact','result'],'result_hold_frames':12},'transition':{'beat_id':'B1','offset_frames':0,'tolerance_frames':2},'sfx_cues':[{'cue_id':'hit','action_frame':48,'tolerance_frames':2}],'readability':[{'element_id':'evidence','text':'6000','min_pixel_height':24}]}
  if mutate:mutate(timeline,recipe)
  timeline_path=root/'timeline.json';timeline_path.write_text(json.dumps(timeline));timeline_sha=hashlib.sha256(timeline_path.read_bytes()).hexdigest();common={'candidate_sha256':digest,'project_id':'P1','project_version':'V1','timeline_provenance':{'timeline_evidence_sha256':timeline_sha}}
  docs={'agentcut_materialized_timeline':timeline,'agentcut_render_plan':{**common,'clips':[{'clip_id':'C1','recipe_id':'R1'}]},'shot_recipe_registry':{**common,'recipes':[recipe]},'beat_grid':{**common,'beats':[{'beat_id':'B1','frame':72}]},'sfx_cue_manifest':{**common,'cues':[{'cue_id':'hit','clip_id':'C1','frame':48}]}}
  evidence={}
  for key,data in docs.items():
   if key in omit:continue
   target=timeline_path if key=='agentcut_materialized_timeline' else root/f'{key}.json'
   if key!='agentcut_materialized_timeline':
    if stale==key:data['timeline_provenance']['timeline_evidence_sha256']='0'*64
    target.write_text(json.dumps(data))
   evidence[key]=str(target)
  item={'path':str(media),'kind':'video','scope':'shot','clip_id':'C1','evidence_inputs':evidence}
  return d,media,item
 def audit(self, mutate=None, omit=(), stale=None, required=()):
  d,media,item=self.fixture(mutate,omit,stale);item['required_capabilities']=list(required);issues,caps,audit=audit_shot_recipe(media,item,4,stable_issue);return d,issues,caps,audit,item
 def test_slow_push_complete_phases_and_result_hold_pass(self):
  d,issues,caps,audit,_=self.audit();self.assertEqual(issues,[]);self.assertEqual(audit['status'],'PASS');self.assertEqual(caps['motion_arc_audit']['status'],'PASS');self.assertEqual(caps['shot_recipe_conformance']['status'],'PASS');d.cleanup()
 def test_official_agentcut_camelcase_nested_sidecar_all_six_caps_pass(self):
  d,media,item=self.official_fixture();issues,caps,audit=audit_shot_recipe(media,item,3,stable_issue);self.assertEqual(issues,[]);self.assertEqual(audit['status'],'PASS');self.assertTrue(all(x['status']=='PASS' for x in caps.values()),caps);d.cleanup()
 def test_official_shared_envelope_candidate_mismatch_is_stale_evidence(self):
  d,media,item=self.official_fixture(stale=True);issues,caps,audit=audit_shot_recipe(media,item,3,stable_issue);self.assertEqual(issues,[]);self.assertEqual(audit['status'],'ERROR');self.assertTrue(all(x['status']=='ERROR' and x['error_code']=='STALE_EVIDENCE' for x in caps.values()),caps);d.cleanup()
 def test_planned_motion_missing_fails(self):
  d,issues,caps,_,_=self.audit(lambda timeline,recipe:timeline['clips'][0]['actual'].__setitem__('camera_motion',{'type':'static'}));self.assertEqual(caps['motion_arc_audit']['status'],'FAIL');self.assertTrue(any(x['rule_id']=='shot_recipe.camera_motion_missing' for x in issues));d.cleanup()
 def test_action_result_missing_fails(self):
  def mutate(timeline,recipe):timeline['clips'][0]['actual']['action_phases']=[{'phase':'setup','end_frame':20},{'phase':'contact','end_frame':48}]
  d,issues,caps,_,_=self.audit(mutate);issue=next(x for x in issues if x['rule_id']=='shot_recipe.action_phase_missing');self.assertEqual(issue['recipe_phase'],'result');self.assertEqual(caps['shot_recipe_conformance']['status'],'FAIL');d.cleanup()
 def test_beat_delta_over_threshold_fails(self):
  d,issues,caps,_,_=self.audit(lambda timeline,recipe:timeline['clips'][0]['actual'].__setitem__('transition_frame',80));issue=next(x for x in issues if x['rule_id']=='shot_recipe.transition_beat_misaligned');self.assertEqual(issue['delta'],8);self.assertEqual(caps['beat_sync_audit']['status'],'FAIL');d.cleanup()
 def test_sfx_misalignment_and_stale_manifest_fail_closed(self):
  d,issues,caps,_,_=self.audit(lambda timeline,recipe:timeline['clips'][0]['actual'].__setitem__('sfx_peaks',[{'cue_id':'hit','frame':60,'motivated':True}]));self.assertTrue(any(x['rule_id']=='shot_recipe.sfx_cue_misaligned' for x in issues));self.assertEqual(caps['sfx_cue_audit']['status'],'FAIL');d.cleanup()
  d,issues,caps,_,_=self.audit(stale='sfx_cue_manifest');self.assertEqual(caps['sfx_cue_audit']['status'],'ERROR');self.assertEqual(caps['sfx_cue_audit']['error_code'],'STALE_EVIDENCE');d.cleanup()
 def test_old_project_is_optional_not_run_without_score_pollution(self):
  d,media,item=self.fixture();item['evidence_inputs']={};issues,caps,_=audit_shot_recipe(media,item,4,stable_issue);self.assertEqual(issues,[]);self.assertTrue(all(cap['status']=='NOT_RUN' and cap['requirement']=='OPTIONAL' for cap in caps.values()));self.assertEqual(score_issues(issues)['score'],5.0);d.cleanup()
 def test_required_missing_evidence_is_capability_fail(self):
  from unittest.mock import patch
  d,media,item=self.fixture();item.update({'evidence_inputs':{},'production_profile':'shot_recipe_conformance_v1'})
  probe_result={'available':True,'format':{'duration':4},'streams':[{'codec_type':'video'},{'codec_type':'audio'}]}
  with patch('qingshan_review.core.probe',return_value=probe_result),patch.object(Reviewer,'_video_external',return_value=([],{'status':'PASS'},None)),patch.object(Reviewer,'_ocr_evidence',return_value=([],{'status':'NOT_RUN'})),patch.object(Reviewer,'_audio',return_value=[]),patch.object(Reviewer,'_ambience',return_value=([],None)),patch.object(Reviewer,'_regressions',return_value=[]):report=Reviewer().review(item)
  self.assertEqual(report['status'],'CAPABILITY_FAIL');self.assertEqual(report['content_status'],'CAPABILITY_FAIL');self.assertIn('shot_recipe_conformance',report['required_capability_failures']);d.cleanup()
 def test_beat_and_sfx_missing_evidence_are_capability_not_content_findings(self):
  d,issues,caps,_,_=self.audit(omit=('beat_grid','sfx_cue_manifest'),required=('beat_sync_audit','sfx_cue_audit'));self.assertFalse(any(x['rule_id'] in {'shot_recipe.transition_beat_misaligned','shot_recipe.sfx_cue_misaligned'} for x in issues));self.assertEqual(caps['beat_sync_audit']['status'],'NOT_RUN');self.assertEqual(caps['sfx_cue_audit']['status'],'NOT_RUN');d.cleanup()
 def test_unauthorized_black_fails_and_provenance_authorized_black_passes(self):
  from unittest.mock import patch
  import hashlib,subprocess
  d=tempfile.TemporaryDirectory();media=Path(d.name)/'black.mp4';media.write_bytes(b'black');stderr='[Parsed_blackframe_0] frame:17 pblack:100 pts:11333 t:0.708313 type:I last_keyframe:17\nframe=   48 fps=0.0\n';reviewer=Reviewer();reviewer.ffmpeg='/fake/ffmpeg'
  legacy={'allowed_black_frames':[{'frame':17,'reason':'legacy','confidence':1}]}
  with patch('qingshan_review.core.subprocess.run',return_value=subprocess.CompletedProcess([],0,'',stderr)):issues,cap=reviewer._black_frame_scan(media,legacy,2)
  self.assertEqual(cap['status'],'FAIL');self.assertEqual(len(issues),1)
  authorization={'effect':'black','start_frame':17,'end_frame':17,'reason':'approved transition','approved_policy':'P1','candidate_sha256':hashlib.sha256(media.read_bytes()).hexdigest(),'timeline_evidence_sha256':'a'*64,'provenance_status':'PASS','recipe_id':'R1','clip_id':'C1'}
  with patch('qingshan_review.core.subprocess.run',return_value=subprocess.CompletedProcess([],0,'',stderr)):issues,cap=reviewer._black_frame_scan(media,{'_intentional_effect_authorizations':[authorization]},2)
  self.assertEqual(issues,[]);self.assertEqual(cap['status'],'PASS');self.assertEqual(cap['frames'][0]['adjudication']['approved_policy'],'P1');d.cleanup()
 def test_repair_task_targets_all_intersecting_clips_by_recipe_phase(self):
  issue=stable_issue('shot_recipe.action_phase_missing',Path('/tmp/candidate.mp4'),{'start_seconds':1,'end_seconds':2},'error',1,'restore result',True,details={'clip_id':'C1','recipe_id':'R1','recipe_phase':'result','planned_value':['setup','contact','result'],'measured_value':['setup','contact'],'delta':{'missing_phase':'result'}});issue.update({'clip_id':'C1','recipe_id':'R1','recipe_phase':'result'})
  report={'review_id':'REV-1','issues':[issue],'agentcut':{'metadata':{'status':'NOT_FINAL'},'clips':[{'clip_id':'C1','kind':'video','timeline_range':{'start_seconds':0,'end_seconds':1.5}},{'clip_id':'C2','kind':'video','timeline_range':{'start_seconds':1.5,'end_seconds':3}}]}}
  task=repair_task(report);self.assertEqual(len(task['repairs']),2);self.assertEqual({x['clip_id'] for x in task['repairs']},{'C1','C2'});self.assertTrue(all(x['recipe_phase']=='result' and x['action']=='REPAIR_AGENTCUT_RECIPE_PHASE' and x['publish_allowed'] is False for x in task['repairs']))

class EpisodeRuntimeAndVisualPacingTests(unittest.TestCase):
 def test_episode_runtime_180_plus_10_passes(self):
  p=Path('/tmp/episode.mp4');issues,cap=Reviewer()._episode_runtime(p,{'kind':'video','scope':'final','runtime_policy':{'version':'episode-runtime/2','target_seconds':180,'soft_tolerance_seconds':10,'hard_tolerance_seconds':20}},190);self.assertEqual(issues,[]);self.assertEqual(cap['status'],'PASS');self.assertTrue(cap['passed'])
 def test_episode_runtime_soft_deviation_warns(self):
  p=Path('/tmp/episode.mp4');issues,cap=Reviewer()._episode_runtime(p,{'kind':'video','scope':'final','runtime_policy':{'target_seconds':180,'soft_tolerance_seconds':10,'hard_tolerance_seconds':20}},195);self.assertEqual(cap['status'],'WARN');self.assertFalse(issues[0]['blocking'])
 def test_episode_runtime_hard_deviation_blocks_e36_shape(self):
  p=Path('/tmp/E36_V28.mp4');issues,cap=Reviewer()._episode_runtime(p,{'kind':'video','scope':'final','runtime_policy':{'version':'episode-runtime/2','target_seconds':180,'soft_tolerance_seconds':10,'hard_tolerance_seconds':20}},316.374349);self.assertEqual(cap['status'],'FAIL');self.assertTrue(issues[0]['blocking']);self.assertEqual(issues[0]['rule_id'],'video.episode_runtime_hard_deviation');self.assertAlmostEqual(cap['delta_seconds'],136.374349)
 def test_new_final_missing_runtime_contract_blocks(self):
  p=Path('/tmp/new.mp4');issues,cap=Reviewer()._episode_runtime(p,{'kind':'video','scope':'final','metadata':{'production_contract_version':2}},180);self.assertEqual(cap['status'],'FAIL');self.assertEqual(issues[0]['rule_id'],'video.episode_runtime_plan_missing')
 def test_legacy_final_missing_runtime_contract_is_optional(self):
  p=Path('/tmp/old.mp4');issues,cap=Reviewer()._episode_runtime(p,{'kind':'video','scope':'final'},316);self.assertEqual(issues,[]);self.assertEqual(cap['status'],'NOT_RUN');self.assertEqual(cap['requirement'],'OPTIONAL')
 def test_three_repeated_visual_signatures_fail(self):
  clips=[]
  for i in range(3):clips.append({'clip_id':f'C{i}','kind':'video','timeline_range':{'start_seconds':i*5,'end_seconds':(i+1)*5},'metadata':{'visual_signature':'closeup|table|pointing','natural_unit_id':'U1'}})
  issues,cap=Reviewer()._visual_pacing(Path('/tmp/a.mp4'),{'kind':'video','scope':'final','require_visual_pacing':True},{'clips':clips});self.assertEqual(cap['status'],'FAIL');self.assertTrue(any(x['rule_id']=='video.consecutive_visual_pattern_repeat' for x in issues));self.assertTrue(any(x['rule_id']=='video.natural_unit_source_overload' for x in issues))
 def test_normal_reverse_shots_pass(self):
  clips=[{'clip_id':'A','kind':'video','timeline_range':{'start_seconds':0,'end_seconds':4},'metadata':{'visual_signature':'wide|two-shot','natural_unit_id':'U1'}},{'clip_id':'B','kind':'video','timeline_range':{'start_seconds':4,'end_seconds':8},'metadata':{'visual_signature':'closeup|speaker-a','natural_unit_id':'U1'}},{'clip_id':'C','kind':'video','timeline_range':{'start_seconds':8,'end_seconds':12},'metadata':{'visual_signature':'reaction|speaker-b','natural_unit_id':'U2'}}]
  issues,cap=Reviewer()._visual_pacing(Path('/tmp/a.mp4'),{'kind':'video','scope':'final','require_visual_pacing':True},{'clips':clips});self.assertEqual(issues,[]);self.assertEqual(cap['status'],'PASS')

if __name__=="__main__":unittest.main()
